src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTag/CreateTagCommandHandler.cs
src/Equinor.Procosys.Preservation.MainApi/ITagApiService.cs
src/Equinor.Procosys.Preservation.MainApi/MainApiService.cs
src/Equinor.Procosys.Preservation.WebApi/DiModules/ApplicationModule.cs

Renamed interface to decouple it from the implementation. In the future, tags may come from another source than it does today.

Renamed service interface to clarify its responsibility.

---

src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/PreservationRecord.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/Requirement.cs
src/Equinor.Procosys.Preservation.Domain/DateTimeExtensions.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PersonConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200116131211_MovedNextDueDateColumn.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200116131211_MovedNextDueDateColumn.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/TagAggregate/PreservationRecordTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/TagAggregate/RequirementTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/DateTimeExtensionsTests.cs

Moved NextDueTimeUtc column from PreservationRecord to Requirement.
New method on Requirement: SetNextDueTimeUtc
PreservationRecord.PreservedBy renamed to PreservedByPersonId 
Nullable columns in PreservationRecord made not-nullable, and set via ctor.
Updated unit tests

Move next due date column

---

src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Journey.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/Tag.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/CommandHandlerTestsBase.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/CreateJourney/CreateJourneyCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/CreateStep/CreateStepCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/CreateMode/CreateModeCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/DeleteMode/DeleteModeCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTag/CreateTagCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/SetStep/SetStepCommandHandlerTests.cs

Unit test on all missing CommandHandlers.
Abstract CommandHandlerTestsBase.cs is base on all test classes testing command handlers since IUnitOfWork and IPlantProvider is often needed

Unit test on all command handlers

---

src/Equinor.Procosys.Preservation.Command/TagCommands/RecordValues/RecordValuesCommand.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/RecordValues/RecordValuesCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/RecordValues/RecordValuesCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/Field/FieldValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/Field/IFieldValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/Tag/ITagValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/Tag/TagValidator.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/CheckBoxChecked.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/NumberValue.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/PreservationPeriod.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/IRequirementTypeRepository.cs
src/Equinor.Procosys.Preservation.Infrastructure/Repositories/ProjectRepository.cs
src/Equinor.Procosys.Preservation.Infrastructure/Repositories/RequirementTypeRepository.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/PreservedTagsController.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/RecordValues/RecordCommandTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/RecordValues/RecordValuesCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/RecordValues/RecordValuesCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/FieldValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/NumberValueTests.cs

Bugfix: RecordValuesCommand/endpoint must have RequirementId, not RequirementDefinitionId.
Validating legal field values for Number and ChecboxFields
FieldValidator.VerifyFieldType not in use. Removed
IRequirementTypeRepository.GetRequirementDefinitionByFieldIdAsync not in use. Removed

71263 validate values for recording

---

src/Equinor.Procosys.Preservation.Query/GetTagRequirements/GetTagRequirementsQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQuery.cs
src/Equinor.Procosys.Preservation.Query/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/GetUniqueTagRequirementTypes/RequirementTypeDto.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/FilterValues/FilterValuesController.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/FieldValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/JourneyValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/ModeValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/ProjectValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/RequirementDefinitionValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/ResponsibleValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/StepValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActionDetails/GetActionDetailsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagActions/GetTagActionsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagDetails/GetTagDetailsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagRequirements/GetTagRequirementsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/GetTagsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/JourneyAggregate/GetAllJourneysQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/ModeAggregate/GetAllModesQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/GetAllRequirementTypesQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
src/tests/Equinor.Procosys.Preservation.Test.Common/TestDataSet.cs

See comment inside controller about plan and reason for this.
Refactoring:
context.SaveChangesAsync().Wait() in all tests.
Introduced TestDataSet and AddTestDataSet(context) for testing ReadOnly db. Need similar dataset in most tests. Refactor tests to use TestDataSet.
Create Person for current user in ReadOnlyTestsBase.SetupBase

71858 Endpoint getting unique and used requirement types on tags

---

src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj

2 packages were updated in 1 project:
`Microsoft.ApplicationInsights.PerfCounterCollector`, `Microsoft.ApplicationInsights.AspNetCore`
<details>
<summary>Details of updated packages</summary>
NuKeeper has generated a patch update of `Microsoft.ApplicationInsights.PerfCounterCollector` to `2.13.1` from `2.13.0`
`Microsoft.ApplicationInsights.PerfCounterCollector 2.13.1` was published at `2020-02-22T00:45:52Z`, 2 months ago
Updated `src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj` to `Microsoft.ApplicationInsights.PerfCounterCollector` `2.13.1` from `2.13.0`
[Microsoft.ApplicationInsights.PerfCounterCollector 2.13.1 on NuGet.org](https://www.nuget.org/packages/Microsoft.ApplicationInsights.PerfCounterCollector/2.13.1)
NuKeeper has …

Automatic update of 2 packages

---

src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj

NuKeeper has generated a minor update of `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` to `1.10.8` from `1.9.10`
`Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.10.8` was published at `2020-01-28T18:49:29Z`, 3 months ago
Updated `src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj` to `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` `1.10.8` from `1.9.10`
[Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.10.8 on NuGet.org](https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.10.8)
This is an automated update. Merge only if it passes tests
**NuKeeper**: https://github.com/NuKeeperDotNet/NuKeeper

Automatic update of Microsoft.VisualStudio.Azure.Containers.Tools.Targets to 1.10.8

---

src/Equinor.Procosys.Preservation.Domain/EntityBase.cs
src/Equinor.Procosys.Preservation.Domain/Exceptions/ConcurrencyException.cs
src/Equinor.Procosys.Preservation.Infrastructure/EntityConfigurations/Extensions/ConcurrencyTokenConfigurationExtensions.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ActionConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/FieldConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/FieldValueConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/JourneyConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ModeConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PersonConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PreservationPeriodConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PreservationRecordConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ProjectConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/RequirementDefinitionConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/RequirementTypeConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ResponsibleConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/StepConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagFunctionConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagFunctionRequirementConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagRequirementConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200420085753_AddedRowVersion.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200420085753_AddedRowVersion.cs
src/Equinor.Procosys.Preservation.Infrastructure/PreservationContext.cs
src/Equinor.Procosys.Preservation.WebApi/Middleware/GlobalExceptionHandler.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/EntityBaseTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj

Setting the solution up for optimistic concurrency in order to handle conflicts faced with two or more requests updating the same object or the same entity instance.
As of right now this code does not interfere with any of the existing functionality.

71254 optimistic concurrency

---

src/Equinor.Procosys.Preservation.Query/CheckAreaTagNo/CheckAreaTagNoQuery.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/AreaTagDto.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/AreaTagDtoValidator.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs

Bug1: Endpoint didn't have plant as required param
Bug2: Query didn't have IProjectRequest interface (which cause security on Project)
Improvement: Validator -> swagger show which params are required

BUGS on CheckAreaTagNo

---

src/Equinor.Procosys.Preservation.WebApi/Authorizations/ContentRestrictionsChecker.cs
src/Equinor.Procosys.Preservation.WebApi/Authorizations/ProjectAccessChecker.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/ContentRestrictionsCheckerTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/ProjectAccessCheckerTests.cs

When checking access to responsible or project. return false instead of exception when not given (such will happend when client ask for non-existing Tag)

Bugfix when checking access to non-existing Tag id

---

src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Equinor.Procosys.Preservation.Infrastructure.Tests.csproj

NuKeeper has generated a patch update of `MockQueryable.Moq` to `3.1.2` from `3.1.1`
`MockQueryable.Moq 3.1.2` was published at `2020-04-17T16:19:08Z`, 9 days ago
Updated `src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Equinor.Procosys.Preservation.Infrastructure.Tests.csproj` to `MockQueryable.Moq` `3.1.2` from `3.1.1`
[MockQueryable.Moq 3.1.2 on NuGet.org](https://www.nuget.org/packages/MockQueryable.Moq/3.1.2)
This is an automated update. Merge only if it passes tests
**NuKeeper**: https://github.com/NuKeeperDotNet/NuKeeper

Automatic update of MockQueryable.Moq to 3.1.2

---

src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj

NuKeeper has generated a patch update of `Swashbuckle.AspNetCore` to `5.3.3` from `5.3.1`
`Swashbuckle.AspNetCore 5.3.3` was published at `2020-04-20T23:26:42Z`, 7 days ago
Updated `src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj` to `Swashbuckle.AspNetCore` `5.3.3` from `5.3.1`
[Swashbuckle.AspNetCore 5.3.3 on NuGet.org](https://www.nuget.org/packages/Swashbuckle.AspNetCore/5.3.3)
This is an automated update. Merge only if it passes tests
**NuKeeper**: https://github.com/NuKeeperDotNet/NuKeeper

Automatic update of Swashbuckle.AspNetCore to 5.3.3

---

src/Equinor.Procosys.Preservation.Command/TagCommands/StartPreservation/StartPreservationCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/StopPreservation/StopPreservationCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/StartPreservation/StartPreservationCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/StopPreservation/StopPreservationCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs

When using StartPreservation command when onboarding Demissie for making StopPreservation, I found that validation logic for checking IsReadyToBeXXXX could be made better to reuse same logic in Tag domain class. Before this PR "same" logic was duplicated both in Tag.cs and in validators

73178 refactor tag validators for start and stop

---

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/Equinor.Procosys.Preservation.Query/GetTags/GetTagsQueryHandler.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/GetTagsQueryHandlerTests.cs

#SITE and #PO area tags do not follow a Journey. Then it is better to **not** show NextMode or NextResponsible in Transfer dialog if user try to transfer such tags

73419 Bugfix: No NextMode or NextResposible if Tag do not follow a Journey

---

src/Equinor.Procosys.Preservation.Command/TagCommands/CompletePreservation/CompletePreservationCommand.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/CompletePreservation/CompletePreservationCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/CompletePreservation/CompletePreservationCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/StartPreservation/StartPreservationCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/PreservationPeriodStatus.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/TagRequirement.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200429183340_RemovePreservationPeriodStatusStopped.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200429183340_RemovePreservationPeriodStatusStopped.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CompletePreservation/CompletePreservationCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CompletePreservation/CompletePreservationCommandTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CompletePreservation/CompletePreservationCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/PreservationPeriodTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/RequirementTests.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/AccessValidatorTests.cs

Since domain logic say that we Complete the preservation rather than Stop, we rename stuff in code to reflect just this
Removed the enum PreservationPeriodStatus.Stopped (Do not need)
This caused a minor migration.

73422 rename stop to complete

---

src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj
src/tests/Equinor.Procosys.Preservation.Command.Tests/Equinor.Procosys.Preservation.Command.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Equinor.Procosys.Preservation.Infrastructure.Tests.csproj
src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Equinor.Procosys.Preservation.MainApi.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Query.Tests/Equinor.Procosys.Preservation.Query.Tests.csproj
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Equinor.Procosys.Preservation.WebApi.Tests.csproj

3 packages were updated in 7 projects:
`Microsoft.NET.Test.Sdk`, `Microsoft.ApplicationInsights.PerfCounterCollector`, `Microsoft.ApplicationInsights.AspNetCore`
<details>
<summary>Details of updated packages</summary>
NuKeeper has generated a minor update of `Microsoft.NET.Test.Sdk` to `16.6.1` from `16.5.0`
`Microsoft.NET.Test.Sdk 16.6.1` was published at `2020-04-24T09:53:18Z`, 9 days ago
6 project updates:
Updated `src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj` to `Microsoft.NET.Test.Sdk` `16.6.1` from `16.5.0`
Updated `src/tests/Equinor.Procosys.Preservation.Command.Tests/Equinor.Procosys.Preservation.Command.Tests.csproj` to `Microsoft.NET.Test.Sdk` `16.6.1` from `16.5.0`
Updated …

Automatic update of 3 packages

---

src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ProjectConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/RequirementTypeConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/StepConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagFunctionRequirementConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagRequirementConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200504125235_MovedStepConfigToTag.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200504125235_MovedStepConfigToTag.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200504132707_ChangedSomeDeleteBehaviorCascadeToNoAction.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200504132707_ChangedSomeDeleteBehaviorCascadeToNoAction.cs

Changed some .OnDelete(DeleteBehavior.Cascade) which has been made as default configuration to explicit .OnDelete(DeleteBehavior.NoAction).
We will pragmatically implement delete if needed. This to prevent accidental cascade deletes in database
Also "moved" builder.HasMany<Tag>(); from StepConfiguration to builder.HasOne<Step>() in TagConfiguration. (Generated code inside snapshot not changed due to this particular change)

70814 Cascade delete mode

---

src/Equinor.Procosys.Preservation.Command/JourneyCommands/UpdateJourney/UpdateJourneyCommand.cs
src/Equinor.Procosys.Preservation.Command/JourneyCommands/UpdateJourney/UpdateJourneyCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/ModeCommands/UpdateMode/UpdateModeCommand.cs
src/Equinor.Procosys.Preservation.Command/ModeCommands/UpdateMode/UpdateModeCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTag/UpdateTagCommand.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTag/UpdateTagCommandHandler.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/UpdateJourney/UpdateJourneyCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/UpdateMode/UpdateModeCommandHandlerTests.cs

Small update to backend to make front-end be able to do multiple puts without refresh, as the updated row version must be returned.

Returning updated row version

---

src/Equinor.Procosys.Preservation.Command/ActionCommands/CloseAction/CloseActionCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/ActionCommands/UpdateAction/UpdateActionCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/UpdateRequirements/UpdateRequirementsCommandHandler.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ActionCommands/CloseAction/CloseActionCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ActionCommands/UpdateAction/UpdateActionCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/UpdateJourney/UpdateJourneyCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/UpdateStep/UpdateStepCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/UpdateMode/UpdateModeCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CompletePreservation/CompletePreservationCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTag/UpdateTagCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagFunctionCommands/UpdateRequirements/UpdateRequirementsCommandHandlerTests.cs

Yesterday we found a better way to test RowVersion flow in Handlers.
This PR is to uniform these tests even more.
**PS: Writing these tests, I also found bug in both CloseActionCommandHandler.cs and UpdateActionCommandHandler.cs. They returned RowVersion.ToString(), which is "System.Byte[]"**

Uniform more row version tests

---

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagConfiguration.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200518131838_AddColumnTagStatusEnum.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200518131838_AddColumnTagStatusEnum.cs

Tag.Status is an Enum with 3 possible values: NotStarted, Active and Completed.
Today we've chosen to store this as string in DB. We convert to int: 0, 1 or 2
In next PR I'll throw old Status-column rename StatusEnum back to Status.
Then we can use Status for sorting + implement better disaplayvalues (as "Not started")

73869 - First part of converting Tag.Status

---

src/Equinor.Procosys.Preservation.Command/MiscCommands/Clone/CloneCommand.cs
src/Equinor.Procosys.Preservation.Command/MiscCommands/Clone/CloneCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/MiscCommands/Clone/CloneCommandValidator.cs
src/Equinor.Procosys.Preservation.Domain/IPlantProvider.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Misc/CloneController.cs
src/Equinor.Procosys.Preservation.WebApi/Misc/PlantProvider.cs
src/Equinor.Procosys.Preservation.WebApi/Seeding/SeedingPlantProvider.cs

Endpoint for cloning Library data from one plant to another.
Not allowed to clone into a BASIS plant.
User must have LIBRARY_PRESERVATION/CREATE permission (privilege) to **target** plant. Read access (LIBRARY_PRESERVATION/READ) to **source** plant not checked, but can be checked in validator. I'm not sure that is important here in this context.
Affected Tables:
- Modes
- Responsibles
- RequirementsTypes, including RequirementsDefinitions and Fields
- TagFunctions, including TagFunctionsRequirements

74112 clone endpoint

---

src/Equinor.Procosys.Preservation.Query/TagApiQueries/SearchTags/ProcosysTagDto.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/TagApiQueries/SearchTags/ProCoSysTagDtoTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/TagApiQueries/SearchTags/SearchTagsByTagFunctionQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/TagApiQueries/SearchTags/SearchTagsByTagNoQueryHandlerTests.cs

Breaking change for client, but coordinated with UI dev

Rename from PurchaseOrderNumber to PurchaseOrderTitle in dto

---

src/Equinor.Procosys.Preservation.Command/SyncCommands/SyncProjects/SyncProjectsCommand.cs
src/Equinor.Procosys.Preservation.Command/SyncCommands/SyncProjects/SyncProjectsCommandHandler.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/Equinor.Procosys.Preservation.Domain/IPermissionCache.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200617062759_UpdateEventTypeConstrains.Designer.cs
src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200617062759_UpdateEventTypeConstrains.cs
src/Equinor.Procosys.Preservation.Infrastructure/Repositories/ProjectRepository.cs
src/Equinor.Procosys.Preservation.MainApi/Client/BearerTokenApiClient.cs
src/Equinor.Procosys.Preservation.MainApi/Project/ProcosysProject.cs
src/Equinor.Procosys.Preservation.WebApi/Caches/PermissionCache.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Synchronize/SynchronizeController.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/ActionCommands/CloseAction/CloseActionCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/CommandHandlerTestsBase.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/SyncCommands/SyncProjects/SyncProjectsCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/BulkPreserve/BulkPreserveCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Preserve/PreserveCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Repositories/ProjectRepositoryTests.cs
src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Client/BearerTokenApiClientTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/ClaimsTransformationTests.cs

Command supposed to be called from background job. In this PR its also possible to trigger the command from a normal endpoint in SynchronizeController. Logic in Handler:
* For all projects in preservation where user has access to project (checked via IPermissionCache)
* Get updated project details from Main and update properties we've duplicated into preservation
* For project, get all standard preservation tags in it (we can skip Area tags since the've been created in preservation and never exists in Main)
* Page 50 and 50 for standard tags and get updated tag details from Main and update properties we've duplicated into preservation
We don't check if property has been chaanged since EF Core keep track of changes and don't save if no changes
Removed …

74436 Sync Projects and Tags with Main

---

src/Equinor.Procosys.Preservation.WebApi/Middleware/GlobalExceptionHandler.cs

This PR also covers review of commit https://github.com/equinor/procosys-preservation-api/commit/5e307665185f99603fd26880136d6ded7efb415f which was committed to Master without purpose.
Commit message other commit:
"Rewrite GlobalExceptionHandler in catch of ValidationException to return a json of type ValidationProblemDetails. This is what ASP.NET Core do when validating Controller inputs.
We want to return same json structure after business validation errors so client have one structure to handle after all type of 400-errors"

74884-Uniform Json after validation errors (errorcode 400)

---

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateAreaTag/CreateAreaTagCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/RequirementForCommand.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/IRequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/RequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateAreaTag/CreateAreaTagCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/RequirementDefinitionValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs

When starting to fix error and write more unit tests, I noticed that the `UpdateTagStepAndRequirementsCommandValidator` didn't handle all scenarios to ensure that a Tag will always have a requirement in any Step after voiding of requirements. 
The `UpdateTagStepAndRequirementsCommandValidator` was also written in a manner that it didn't check already persisted Requirements on the tag, and align those together with list of requirements to be voided/added in the `UpdateTagStepAndRequirementsCommand`. Therefor the validation methods are moved from `IRequirementDefinitionValidator` to `ITagValidator`
A lot of new unit tests written to check all these odd cornercases

74973 Update validator to prohibit voiding of all requirements

---

src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj

NuKeeper has generated a patch update of `Swashbuckle.AspNetCore` to `5.5.1` from `5.5.0`
`Swashbuckle.AspNetCore 5.5.1` was published at `2020-06-25T21:16:00Z`, 7 days ago
Updated `src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj` to `Swashbuckle.AspNetCore` `5.5.1` from `5.5.0`
[Swashbuckle.AspNetCore 5.5.1 on NuGet.org](https://www.nuget.org/packages/Swashbuckle.AspNetCore/5.5.1)
This is an automated update. Merge only if it passes tests
**NuKeeper**: https://github.com/NuKeeperDotNet/NuKeeper

Automatic update of Swashbuckle.AspNetCore to 5.5.1

---

src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommand.cs
src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommandHandler.cs
src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/IRequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/RequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/IRequirementTypeRepository.cs
src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementType.cs
src/Equinor.Procosys.Preservation.Infrastructure/Repositories/RequirementTypeRepository.cs
src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/GetAllRequirementTypesQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/GetRequirementTypeByIdQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/RequirementDefinitionDto.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/DeleteRequirementDefinitionDto.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/RequirementTypesController.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/MiscCommands/Clone/RequirementTypeRepository.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/RequirementDefDtoTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/RequirementTypeDtoTests.cs

Delete requirement definition.
Have deleteRequirementDefinition in RequirementTypeRepository because using remove as on DeleteStep does not delete object from database (just removes parentId). (ParentId on requirementDefinition is not nullable in database, so would have to change this if we wanted to remove requirement definition in the same way as we are "removing" step for example). 
Need to create composite key to achieve a complete delete, and can then remove this remove method from 
RequirementTypeRepository. The composite key for Requirement Definition would be Id and RequirementTypeId.

75278: Delete requirement definition

---

src/Equinor.Procosys.Preservation.WebApi/Program.cs

Before fix, application throw exception (413 request entity too large) before our endpoint is reached and the response caused CORS error in client (Therefore "Unknown error")
The new codeline turn off the verification of request body size and we can verify uploaded file our self. We check for valid file type + filesize < 100Mb
limit seemed to be approx 20-30Mb in localhost, only 1Mb Dev and Test

75233 - Unknown Error when uploading large files

---

src/Equinor.Procosys.Preservation.WebApi/Authorizations/ClaimsExtensions.cs
src/Equinor.Procosys.Preservation.WebApi/Middleware/VerifyOidInDbMiddleware.cs

Doing the same "magic" as ad sync when handling affiliate user without first name and last name

Handling users without firstname and lastname

---

src/Equinor.Procosys.Preservation.BlobStorage/Equinor.Procosys.Preservation.BlobStorage.csproj
src/Equinor.Procosys.Preservation.Command/Equinor.Procosys.Preservation.Command.csproj
src/Equinor.Procosys.Preservation.Infrastructure/Equinor.Procosys.Preservation.Infrastructure.csproj
src/Equinor.Procosys.Preservation.MainApi/Equinor.Procosys.Preservation.MainApi.csproj
src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj
src/tests/Equinor.Procosys.Preservation.Command.Tests/Equinor.Procosys.Preservation.Command.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Equinor.Procosys.Preservation.Infrastructure.Tests.csproj
src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Equinor.Procosys.Preservation.MainApi.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Query.Tests/Equinor.Procosys.Preservation.Query.Tests.csproj
src/tests/Equinor.Procosys.Preservation.Test.Common/Equinor.Procosys.Preservation.Test.Common.csproj
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Equinor.Procosys.Preservation.WebApi.Tests.csproj

22 packages were updated in 12 projects:
`Moq`, `Microsoft.Extensions.Logging.Abstractions`, `Microsoft.Extensions.Options`, `Microsoft.Extensions.Caching.Memory`, `Microsoft.EntityFrameworkCore`, `Microsoft.EntityFrameworkCore.InMemory`, `FluentValidation`, `FluentValidation.AspNetCore`, `Azure.Storage.Blobs`, `Microsoft.ApplicationInsights.PerfCounterCollector`, `Microsoft.ApplicationInsights.AspNetCore`, `Microsoft.Identity.Client`, `Microsoft.Extensions.Http`, `Microsoft.AspNetCore.Authentication.JwtBearer`, `Microsoft.AspNetCore.Authentication.MicrosoftAccount`, `Microsoft.AspNetCore.Authentication.OpenIdConnect`, `Microsoft.EntityFrameworkCore.Design`, `Microsoft.Extensions.Configuration.AzureKeyVault`, `Microsoft.EntityFrameworkCore.SqlServer`, …

Automatic update of 22 packages

---

src/Equinor.Procosys.Preservation.Command/SyncCommands/SyncProjects/SyncProjectsCommandHandler.cs
src/Equinor.Procosys.Preservation.Domain/IPermissionCache.cs
src/Equinor.Procosys.Preservation.MainApi/Permission/IPermissionApiService.cs
src/Equinor.Procosys.Preservation.MainApi/Permission/MainApiPermissionService.cs
src/Equinor.Procosys.Preservation.MainApi/Permission/ProcosysProject.cs
src/Equinor.Procosys.Preservation.WebApi/Authorizations/ClaimsTransformation.cs
src/Equinor.Procosys.Preservation.WebApi/Behaviors/CheckValidProjectBehavior.cs
src/Equinor.Procosys.Preservation.WebApi/Caches/PermissionCache.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Misc/CacheController.cs
src/Equinor.Procosys.Preservation.WebApi/DiModules/ApplicationModule.cs
src/Equinor.Procosys.Preservation.WebApi/DiModules/MediatorModule.cs
src/Equinor.Procosys.Preservation.WebApi/Middleware/CurrentPlantMiddleware.cs
src/Equinor.Procosys.Preservation.WebApi/Middleware/GlobalExceptionHandler.cs
src/Equinor.Procosys.Preservation.WebApi/Middleware/PlantValidatorMiddleware.cs
src/Equinor.Procosys.Preservation.WebApi/Misc/HttpContextExtension.cs
src/Equinor.Procosys.Preservation.WebApi/Misc/IProjectChecker.cs
src/Equinor.Procosys.Preservation.WebApi/Misc/InValidProjectException.cs
src/Equinor.Procosys.Preservation.WebApi/Misc/ProjectChecker.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/SyncCommands/SyncProjects/SyncProjectsCommandHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Plant/MainApiPlantServiceTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/ClaimsTransformationTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Caches/PermissionCacheTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Caches/PlantCacheTests.cs

Part 2 of #425
The goal for this change is to distinguish between accessing a invalid project vs a project where user don't have access.
* Refactor IPermissionApiService -> GetAllProjectsAsync now get all projects, also those where user don't have access. New property ProcosysProject.HasAccess tell if user has access
* Refactored CurrentPlantMiddleware. Throw exception, not return BadRequest, if headers can't be found. This **IS** unexcepted. 
* New behavior in MediatR pipeline: If request is requesting data froma project, check if that project is a valid one. Return BadRequest if not valid. 
* HttpContextExtension which write a correct BadRequest json back to client. Also used in PlantValidatorMiddleware made in prev PR
* NB! Sequence of behaviors changed. Validate query/command before …

78680 Use new project features from main api

---

src/Equinor.Procosys.Preservation.Command/EventHandlers/HistoryEvents/StepChangedEventHandler.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/StepChangedEventHandlerTests.cs

Could not call StepChangedEventHandler.Handle async. Got System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext

78422 bug when saving tag updates

---

src/Equinor.Procosys.Preservation.WebApi/Controllers/Modes/ModesController.cs

Since client works as is, this is **NOT** considered as a breaking change

79188 - Get Modes - Return list of Dtos

---

src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/UnvoidRequirementDefinition/UnvoidRequirementDefinitionCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/UpdateRequirementDefinition/UpdateRequirementDefinitionCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/VoidRequirementDefinition/VoidRequirementDefinitionCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/IRequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/RequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementTypeValidators/IRequirementTypeValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementTypeValidators/RequirementTypeValidator.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/CreateRequirementDefinitionDto.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/DeleteRequirementDefinition/DeleteRequirementDefinitionCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/UnvoidRequirementDefinition/UnvoidRequirementDefinitionCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/UpdateRequirementDefinition/UpdateRequirementDefinitionCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/VoidRequirementDefinition/VoidRequirementDefinitionCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/RequirementDefinitionValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/KnownTestData.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/FieldDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementDefinitionDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypeDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerNegativeTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerTestsBase.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerTestsHelper.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs

Same stuff for how validating if Req Def exists under a Req Type.
In my point of view, the codereview of int.tests can be done with one eye.
IRequirementDefinitionValidator.RequirementDefinitionHasRequirementTypeAsParentAsync removed. Not in use now
Hang in there .... this is the second last one :-p

77899 how validator check when children exists vol4

---

src/Equinor.Procosys.Preservation.Command/TagCommands/CompletePreservation/CompletePreservationCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs
src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CompletePreservation/CompletePreservationCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/KnownTestData.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/IdAndRowVersion.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsBase.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestFactory.cs

Fixed CompletePreservationCommandValidator and TransferCommandValidator to ensure given RowVersion from client is a real RowVersion. Covered by new int. tests
No need to review int.tests

79800 row version validation

---

src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestBase.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestFactory.cs

Minor adjustment needed, found when implementing for IPO. If not disposing in TestBase, DB remains on local disk.
Each test solution should also use differerent CatalogNames for created test DB. If not, this cause problem if test db for other solution remains on local DB from last run.

79984 - Fix in test teardown do delete created Test DB

---

src/Equinor.Procosys.Preservation.Query/GetHistory/GetHistoryQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportHistoryDto.cs
src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportTagDto.cs
src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/GetTagsQueries/TagForQueryDto.cs
src/Equinor.Procosys.Preservation.WebApi/Excel/ExcelConverter.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActionAttachments/GetActionAttachmentsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActionDetails/GetActionDetailsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActions/GetActionsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetFieldValueAttachment/GetFieldValueAttachmentQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetHistoricalFieldValueAttachment/GetHistoricalFieldValueAttachmentQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetHistory/GetHistoryQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagAttachment/GetTagAttachmentQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagAttachments/GetTagAttachmentsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagDetails/GetTagDetailsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagRequirements/GetTagRequirementsQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/IntegrationTestAuthHandler.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PersonDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/ActionDetailsDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/HistoryDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestFactory.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestProfile.cs

Main task is to create History sheet in Excel. The sheet is created only when 1 tag filtered in query.
During work a minor improvement was done in GetHistory endpoint: The endpoint now return 404 for unknown Tag instead of empty list of History records
Improvements done in integration test framework regading handling of FirstName and LastName in claims and bearertoken (these improvements can/should be taken into IPO too)

80306 history tab in excel

---

src/Equinor.Procosys.Preservation.Query/GetPreservationRecord/GetPreservationRecordQueryHandler.cs
src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetPreservationRecord/GetPreservationRecordQueryHandlerTests.cs
src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs

Bugfix 1 when creating Excel with details: 
Need to handle that FieldValues for all Fields in a Requirement Def don't have to exists for all preservation periods since a field can be added to a Requirement Def after preservation periods are made
Bugfix 2: GetPreservationRecordQueryHandler - The interval was taken from the Requirement Definition, not from the actual TagRequirement (showed wrong in UI)

80421 details in history in excel bugfix

---

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs

BUG found while working with Delete Tag Requirement:
In Tag.UpdateRequirement when Voiding: Need to re-calculate next due on both Void and Unvoid. Tests added.
[AB#79034](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/79034)

79034 delete tagrequirement bugfix

---

src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/PersonsController.cs

Part 1 of 2 for fixing routes under Persons controller. 
This part adds the new endpoints to be used instead of the old ones. Old ones are not removed.
[AB#80991](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/80991)

80991 fix routes in preservation vol 1

---

src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/PersonsController.cs

Part 2/2 of fixing routes under Persons controller.
This part removes the old routes which didn't have the /Persons prefix.
[AB#80991](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/80991)

80991-fix routes in preservation vol2

---

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateAreaTag/CreateAreaTagCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/IRequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/RequirementDefinitionValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs
src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateAreaTag/CreateAreaTagCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/RequirementDefinitionValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Journeys/ModeDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Journeys/StepDto.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/KnownTestData.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsBase.cs
src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs

Changes in rules when creating / editing a PO Area tag. The BUG is that rules in current version of API, require that user add both requirement which is valid in an supplier step AND in a non supplier step. 
Since a PO Area tag has the characteristics that such tag MUST exist in a suppløier step (and can't be transferred), the requirement to add a requirement which is valid in an non supplier step is meaningless. 
Rules changed to ensure that for PO Area tag, it's OK with requirement valid in supplier step only
[AB#82120](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82120)

82120 allow supplier requirement only for PO

---

src/Equinor.ProCoSys.Preservation.BlobStorage/Equinor.ProCoSys.Preservation.BlobStorage.csproj
src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj
src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj
src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj
src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj

FluentValidation NOT upgraded. MicroElements.Swashbuckle.FluentValidation need 
FluentValidation < 10.0.0
[AB#82524](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82524)

82524 - Upgrade Nuget Pkgs (minus FluentValidation)

---

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs

Quick fix to bypass messages if project is not relevant for preservation.

Fixing logic glitch

---

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs

[AB#83491](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/83491)
Bug was: Any tag which had been voided showed up in the unvoided list a week later. 
Solution: Sync bus wrongfully set tag isvoided, this was not done in the prior sync solution. 'Voiding' a tag in preservation is not the same thing as voiding a tag in main, so this property will be ignored in preservation.

83491 Voided tags active after a week bugfix

---

src/Equinor.ProCoSys.Preservation.Query/GetTagDetails/GetTagDetailsQueryHandler.cs
src/Equinor.ProCoSys.Preservation.WebApi/Properties/launchSettings.json

Improve generated sql due to bad performance when tag has many actions and/or attachments. The generated sql with existing code, produced over 30000 rows to get 1 tag!
[AB#85750](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/85750)

85750 - bad performance getting tag w many actions and/or attachments

---

src/Equinor.ProCoSys.Preservation.BlobStorage/Equinor.ProCoSys.Preservation.BlobStorage.csproj
src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj
src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj
src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj
src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj

Removed deprecated Microsoft.Extensions.Configuration.AzureKeyVault.
Alternative Azure.Extensions.AspNetCore.Configuration.Secrets **not** installed since solution build without it.
Upgraded all other packages

90648 - Upgrade NuGet packages

---

src/Equinor.ProCoSys.Preservation.Command/TagCommands/AutoTransfer/AutoTransferCommand.cs
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Authorizations/AccessValidatorTests.cs

In AutoTransfer context it's legal to try to autotransfer on unknown projects
[AB#91017](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/91017)

91017 - AutoTransferCommand must not inherit IProjectRequest

---

src/Equinor.ProCoSys.Preservation.Command/TagCommands/SyncTagData/SyncTagDataCommandHandler.cs
src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs

Sync ProCoSysGuids into preservation DB again since there was a BUG in Main API, which delivered wrong Guids. Existing Guids already populated into preservation will be cleared by a manual script (No automation by migration)
[AB#96688](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96688)

96688 - Sync ProCoSysGuids again

---

src/Equinor.ProCoSys.Preservation.Query/GetJourneyById/GetJourneyByIdQueryHandler.cs
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetJourneyById/GetJourneyByIdQueryHandlerTests.cs

[AB#98580](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98580)
Journey.InUse = any step in use

98580 - Fix JourneyDetailsDto returned by GetJourneyByIdQueryHandler to reflect new rule for Journey.InUse

---

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs
src/Equinor.ProCoSys.Preservation.Infrastructure/Repositories/ProjectRepository.cs
src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs

This will remove the need for old-values in Tag-messages.
McPkg messages and CommPkg messages would still need old-values.  A new feature will be added that enables the removal of this requirement too.

Use GUID instead og OLD-values

---

src/Equinor.ProCoSys.Preservation.MainApi/Tag/MainApiTagService.cs

[AB#107616](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107616)

107616 Correct misspelling of endpoint used in AutoScope

---

radixconfig.yaml

We want to use the same image as was used in deploy
[AB#108176](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/108176)

108176_Remove ImageTagName from promoted environments

---

src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/EventHelpers/CreateProjectTagEventHelper.cs
src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/EventHelpers/CreateResponsibleEventHelper.cs
src/Equinor.ProCoSys.Preservation.Command/Events/ResponsibleEvent.cs
src/Equinor.ProCoSys.Preservation.Command/Events/TagEvent.cs
src/Equinor.ProCoSys.Preservation.MessageContracts/IResponsibleEventV1.cs
src/Equinor.ProCoSys.Preservation.MessageContracts/ITagEventV1.cs
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/EventHandlers/IntegrationEvents/CreateProjectTagEventHelperTests.cs
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/EventHandlers/IntegrationEvents/CreateResponsibleEventHelperTests.cs

Data is received by Preservation over service bus and is used internally. Some of that data was included in integration events that are sent to Alpha. Since Preservation is not the source/owner of that information, that data should not be included in the events.

Removing unowned data from integration events

---

src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj
src/Equinor.ProCoSys.Preservation.Domain/Equinor.ProCoSys.Preservation.Domain.csproj
src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj
src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj
src/Equinor.ProCoSys.Preservation.Query/Equinor.ProCoSys.Preservation.Query.csproj
src/Equinor.ProCoSys.Preservation.WebApi/Dockerfile
src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj

Infra pipeline has been updated to .net 8, causing preservation tests to fail. Fixing by updating the project to version 8.
https://github.com/equinor/cc-toolbox/issues/792

792 pipeline fix

---

src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj
src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj

Running testas was being problematic. Updating the packages resolved the issue.
This is most likely related to recent .net 8 updates.
https://github.com/equinor/cc-toolbox/issues/792

Updating test packages

---

radixconfig.yaml
src/Equinor.ProCoSys.Preservation.Command/ActionAttachmentCommands/Upload/UploadActionAttachmentCommandHandler.cs
src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj
src/Equinor.ProCoSys.Preservation.Command/RequirementCommands/Upload/UploadFieldValueAttachmentCommandHandler.cs
src/Equinor.ProCoSys.Preservation.Command/TagAttachmentCommands/Upload/UploadTagAttachmentCommandHandler.cs
src/Equinor.ProCoSys.Preservation.Query/Equinor.ProCoSys.Preservation.Query.csproj
src/Equinor.ProCoSys.Preservation.Query/GetActionAttachment/GetActionAttachmentQueryHandler.cs
src/Equinor.ProCoSys.Preservation.Query/GetFieldValueAttachment/GetFieldValueAttachmentQueryHandler.cs
src/Equinor.ProCoSys.Preservation.Query/GetHistoricalFieldValueAttachment/GetHistoricalFieldValueAttachmentQueryHandler.cs
src/Equinor.ProCoSys.Preservation.Query/GetTagAttachment/GetTagAttachmentQueryHandler.cs
src/Equinor.ProCoSys.Preservation.Query/UserDelegationProvider/IUserDelegationProvider.cs
src/Equinor.ProCoSys.Preservation.Query/UserDelegationProvider/UserDelegationProvider.cs
src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs
src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/ActionAttachmentCommands/Upload/UploadActionAttachmentCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/RequirementCommands/Upload/UploadFieldValueAttachmentCommandTests.cs
src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagAttachmentCommands/Upload/UploadTagAttachmentCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetActionAttachment/GetActionAttachmentQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetFieldValueAttachment/GetFieldValueAttachmentQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetHistoricalFieldValueAttachment/GetHistoricalFieldValueAttachmentQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagAttachment/GetTagAttachmentQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs

Updating the blob storage package version in order to make use of credential tokens for authentication instead of connection strings.
Completion API change referenced for this update: https://github.com/equinor/procosys-completion-api/pull/266
https://github.com/equinor/cc-toolbox/issues/1066

1066 blob storage update

---

src/Equinor.ProCoSys.Preservation.WebApi/DiModules/SetupDatabase.cs
src/Equinor.ProCoSys.Preservation.WebApi/Program.cs
src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj
src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/SetupDatabaseTests.cs

A previous change removed development configuration options that it should not have been removed. 
https://github.com/equinor/procosys-preservation-api/blob/2f2a9d6daee5f0e3fb67731ace0cd27f2902b44c/src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs#L51
https://github.com/equinor/procosys-preservation-api/pull/1001
https://github.com/equinor/cc-toolbox/issues/1064

1064 re-adding development configuration options

---

src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json

These configurations should have been removed in PR #1014
They have been moved into the application section, and the configurations default to false. Making it redundant to have them in the configuration.
https://github.com/equinor/cc-toolbox/issues/1098

Removing redundant app settings

---

src/Equinor.ProCoSys.Preservation.Infrastructure/Entityconfigurations/ProjectConfiguration.cs

Moving a tag from one project to another existing project was causing an exception in the audit data setter logic (preservation context), when accessing the change tracker.
The error would originate when the tag is removed from a project before being added to another. The entity framework would interpret this as the Tag having been set to null, even through it was added to another project.
Accessing the change tracker would then in turn throw an exception because the tag project cannot be null.
This is likely a bug in EF. I will be following up on that in the associated issue. https://github.com/equinor/cc-toolbox/issues/1642
Replacing the NoAction configuration with ClientCascade fixed the behaviour, and EF no longer attempted to set the project to null.

ClientCascade Project Tag OnDelete NoAction with ClientCascade 
