src/Equinor.Procosys.Preservation.WebApi/Controllers/Journey/JourneysController.cs
Using ID from route, not query.
=> Fixed route.

src/Equinor.Procosys.Preservation.WebApi/Middleware/GlobalExceptionHandler.cs
Added handling and logging of general exceptions.
=> Added handling and logging of general exceptions

src/Equinor.Procosys.Preservation.Infrastructure/Repositories/JourneyRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/RepositoryBase.cs
Setting default query in repository base, reducing the need for overrides.
=> Setting default query in repository base

src/Equinor.Procosys.Preservation.WebApi/Program.cs, src/Equinor.Procosys.Preservation.WebApi/Startup.cs
Enabled Cors for all origins. Removed "Server" header.
=> Cors and headers

src/Equinor.Procosys.Preservation.WebApi/Misc/PlantProvider.cs, src/Equinor.Procosys.Preservation.WebApi/Startup.cs
=> Cors header

src/Equinor.Procosys.Preservation.Command/DateTimeExtensions.cs, src/Equinor.Procosys.Preservation.Command/ITimeService.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/PersonAggregate/IPersonRepository.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/PersonAggregate/Person.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/PreservationRecord.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/Requirement.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Domain/ITimeService.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PersonConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PreservationRecordConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/RequirementConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200115130310_PersonAndPreservationRecord.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200115130310_PersonAndPreservationRecord.cs, src/Equinor.Procosys.Preservation.Infrastructure/PreservationContext.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/PersonRepository.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Heartbeat/HeartbeatController.cs, src/Equinor.Procosys.Preservation.WebApi/Misc/TimeService.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/DateTimeExtensionsTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/PersonAggregate/PersonTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/TagAggregate/PreservationRecordTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Misc/TimeServiceTests.cs
Person and PreservationRecord models w Migration
Tag: Moved props after ctors
=> Person and preservation record models

src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Journey.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Step.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ModeAggregate/Mode.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ResponsibleAggregate/Responsible.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/TagAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200116094745_IsVoided.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200116094745_IsVoided.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/StepTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ModeAggregate/ModeTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/RequirementTypeAggregate/RequirementDefTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/RequirementTypeAggregate/RequirementTypeTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/TagAggregate/RequirementTests.cs
Added IsColumn to Journey, Step, Mode, Responsible, Tag
=> Add IsVoided column to more tables

src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/Field.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementDefinition.cs, src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/FieldDto.cs, src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/GetAllRequirementTypesQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/GetRequirementTypeByIdQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/RequirementDefinitionDto.cs, src/Equinor.Procosys.Preservation.Query/RequirementTypeAggregate/RequirementTypeDto.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/RequirementTypeAggregate/FieldTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/RequirementTypeAggregate/RequirementDefTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/FieldDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/GetRequirementTypesByIdQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/RequirementDefDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/RequirementTypeAggregate/RequirementTypeDtoTests.cs
Moved NeedUserInput from Dto to Domain Objects (Field and RequirementDefinition). 
Need this info pr. Requirement when handling commands (StartPreservation, Preserve, etc.)
Unit tests updated
=> Moved NeedUserInput

src/Equinor.Procosys.Preservation.Domain/DateTimeExtensions.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/DateTimeExtensionsTests.cs
To be used in Requirement dto after merging StartPreservationCommand
=> DateTimeExtensions GetWeeksUntilDate with unit tests

src/Equinor.Procosys.Preservation.Command/TagCommands/Preserve/PreserveCommandHandler.cs, src/Equinor.Procosys.Preservation.Domain/ICurrentUserProvider.cs, src/Equinor.Procosys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.Procosys.Preservation.WebApi/Misc/CurrentUserProvider.cs, src/Equinor.Procosys.Preservation.WebApi/Seeding/Seeder.cs, src/Equinor.Procosys.Preservation.WebApi/Seeding/Seeders.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Preserve/PreserveCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Misc/CurrentUserProviderTests.cs
Added functionality to get the current user.
=> Current user

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTag/CreateTagCommandHandler.cs, src/Equinor.Procosys.Preservation.WebApi/Misc/CurrentUserProvider.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTag/CreateTagCommandHandlerTests.cs
1) Requirements must be created pr tag (i.e inside loop)
2) TagIds to return must be picked after save
=> 2 BUGFIX in CreateTagCommandHandler

src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj, src/Equinor.Procosys.Preservation.WebApi/Startup.cs
Added library to read FluentValidation validators and add the rules to Swagger.
=> FluentValidation validators in Swagger

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Requirement.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Query/ProjectAggregate/GetAllTagsInProjectQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/ProjectAggregate/RequirementDto.cs, src/Equinor.Procosys.Preservation.Query/ProjectAggregate/TagDto.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/RequirementTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/GetAllTagsInProjectQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/RequirementDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/TagDtoTests.cs
Moved logic regarding ReadyToBePreserved from Query to Domain.
Must have both ReadyToBePreserved and ReadyToBeBulkPreserved property pr. Requirement and pr Tag
@arildbjerkenes This is a breaking change on DTO
=> 71225 Bulk-preserve allowed only if due or over due

src/Equinor.Procosys.Preservation.WebApi/Controllers/Modes/ModesController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/CreateAreaTagDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Controllers/Tags/TagsControllerTests.cs
/Preserved removed from routes
=> Rename PreservedTagsController to TagsController

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/TagType.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200214142944_TagType.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200214142944_TagType.cs, src/Equinor.Procosys.Preservation.Query/GetTagDetails/GetTagDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagDetails/TagDetailsDto.cs, src/Equinor.Procosys.Preservation.Query/ProjectAggregate/GetAllTagsInProjectQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/ProjectAggregate/TagDto.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTag/CreateTagCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagDetails/GetTagDetailsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/GetAllTagsInProjectQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/TagDtoTests.cs
Removed IsAreTag and introduced TagType on Tag Domain object.
Migration. Updated unit tests
=> TagType on Tag Domain object

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateAreaTag/CreateAreaTagCommandHandler.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateAreaTag/CreateAreaTagCommandHandlerTests.cs
This is a better temporary solution until we get endpoint in MainApi in later PBI 71457
=> 71253-CreateAreaTag endpoint - Add Project with dummy description.

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Action.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ActionConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/PersonConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200219100527_Action.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200219100527_Action.cs, src/Equinor.Procosys.Preservation.Infrastructure/PreservationContext.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/ActionTests.cs
Action
Tag has list of Actions
Migration of Action
Action will have list of a new Domain entiy: ActionComments. Next PR
=> 71180-Action db model

src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommand.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/Tag/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/Tag/TagValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/IJourneyRepository.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Journey.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Step.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200218102011_StepSortKey.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200218102011_StepSortKey.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/JourneyRepository.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs
Transfer endpoint, TransferCommand handling and validation
=> 71185-Transfer tags

src/Equinor.Procosys.Preservation.Command/Equinor.Procosys.Preservation.Command.csproj, src/Equinor.Procosys.Preservation.Command/RequirementCommands/Preserve/PreserveCommand.cs, src/Equinor.Procosys.Preservation.Command/RequirementCommands/Preserve/PreserveCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/RequirementCommands/Preserve/PreserveCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/RequirementCommands/RecordValues/RecordValuesCommand.cs, src/Equinor.Procosys.Preservation.Command/RequirementCommands/RecordValues/RecordValuesCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/RequirementCommands/RecordValues/RecordValuesCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/Tag/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/Tag/TagValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Requirement.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/RecordValues/RecordCommandTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/RecordValues/RecordValuesCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/RecordValues/RecordValuesCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/BulkPreserve/BulkPreserveCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Preserve/PreserveCommandHandlerTests.cs
* Moved RecordValuesCommand to new namespace RequirementCommands.
* New Endpoint and command for preserving a single Requirement
=> 71483 Preserve one requirement

src/Equinor.Procosys.Preservation.Command/RequirementCommands/Preserve/PreserveCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/RequirementCommands/RecordValues/RecordValuesCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateAreaTag/CreateAreaTagCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTag/CreateTagCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/Preserve/PreserveCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/StartPreservation/StartPreservationCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/RecordValues/RecordValuesCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/ProjectValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
**TagTypeCanBeTransferredAsync in TagValidator and TagTypeCanBeTransferredAsync in TransferCommandValidator is the important stuff here.**
(Other renames found after previous PR's)
=> 71719 Prohibit transfer of site area tags

src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200228140008_RenameStep.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200228140008_RenameStep.cs, src/Equinor.Procosys.Preservation.Infrastructure/PreservationContext.cs
=> 71506 rename table Step to Steps

src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/IJourneyRepository.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ModeAggregate/IModeRepository.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/IRequirementTypeRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/JourneyRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/ModeRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/ProjectRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/RequirementTypeRepository.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/StepValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Repositories/JourneyRepositoryTests.cs, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Repositories/ModeRepositoryTests.cs, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Repositories/ProjectRepositoryTests.cs
After refactoring Validators to not use Repo, some methods became unused. Removed
=> 71622-Remove unused repo methods

src/Equinor.Procosys.Preservation.Query/ProjectAggregate/GetAllTagsInProjectQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/ProjectAggregate/RequirementDto.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/StepValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/GetAllTagsInProjectQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/RequirementDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ProjectAggregate/TagDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
Refactored GetAllTagsInProjectQueryHandler to use IReadOnlyContext.
Enrich RequirementDto with RequirementTypeCode.
Removed obsolete ReadyToBeBulkPreserved from RequirementDto
=> 71264 requirement icons in scope

src/Equinor.Procosys.Preservation.Query/GetTags/ActionFilterType.cs, src/Equinor.Procosys.Preservation.Query/GetTags/ActionStatus.cs, src/Equinor.Procosys.Preservation.Query/GetTags/Filter.cs, src/Equinor.Procosys.Preservation.Query/GetTags/GetTagsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTags/TagDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/FilterDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/FilterTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/GetTagsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/GetTagsQueryTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/TagDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/TagsResultTests.cs
Last 3 filters: On AreaCode, Due and on different states of actions on Tag
Tests
(Filter for Area/Storage will come later .. we don't have such data in out model yet)
=> 71858 more filters

src/Equinor.Procosys.Preservation.Query/JourneyAggregate/GetJourneyByIdQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/GetTagsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/JourneyAggregate/GetJourneyByIdQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/TestDataSet.cs
@llykkelarsen This PR is also fine as a starter for a minor OnBoarding PBI. See PBI 72291.
This PR is first of 4 tasks, where all tasks are similar.
=> 72291 Refactor GetJourneyByIdQueryHandler to use IReadOnlyContext

src/Equinor.Procosys.Preservation.Query/GetUniqueTagModes/GetUniqueTagModesQuery.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagModes/GetUniqueTagModesQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagModes/ModeDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/FilterValues/FilterValuesController.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagJourneys/GetUniqueTagJourneysQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagModes/GetUniqueTagModesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagModes/GetUniqueTagModesQueryTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagResponsibles/GetUniqueTagResponsiblesQueryHandlerTests.cs
Endpoint for unique filter values: Modes
Tests
=> 72144 endpoint for getting unique filter values for modes

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateAreaTag/CreateAreaTagCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTag/CreateTagCommandHandler.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/TagConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200325125443_AddTagDescriptionColumns.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200325125443_AddTagDescriptionColumns.cs, src/Equinor.Procosys.Preservation.WebApi/Seeding/Seeders.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
Extending commands to save values into columns in next PR
=> 71435 Enrich tag table with AreaDescription and DisciplineDescription

src/Equinor.Procosys.Preservation.Query/GetUniqueTagAreas/AreaCodeDto.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagAreas/AreaDto.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagAreas/GetUniqueTagAreasQuery.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagAreas/GetUniqueTagAreasQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagDisciplines/DisciplineDto.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagDisciplines/GetUniqueTagDisciplinesQuery.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagDisciplines/GetUniqueTagDisciplinesQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagFunctions/GetUniqueTagFunctionsQuery.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagFunctions/GetUniqueTagFunctionsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagFunctions/TagFunctionCodeDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/FilterValues/FilterValuesController.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagAreas/GetUniqueTagAreasQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagAreas/GetUniqueTagAreasQueryTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagDisciplines/GetUniqueTagDisciplinesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagDisciplines/GetUniqueTagDisciplinesQueryTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagFunctions/GetUniqueTagFunctionsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagFunctions/GetUniqueTagFunctionsQueryTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagJourneys/GetUniqueTagJourneysQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagModes/GetUniqueTagModesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetUniqueTagResponsibles/GetUniqueTagResponsiblesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
Endpoint for unique filter values:
- Area codes
- Tag function codes
- Discipline codes
Tests
=> 72144 endpoint for unique filter values area tag function dicipline

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommand.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommandValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/CreateTagsDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/CreateTagsDtoValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Controllers/Tags/TagsControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/ProjectAccess/ProjectAccessValidatorTests.cs
=> 72390 Rename CreateTagCommand to plural

src/Equinor.Procosys.Preservation.Command/Validators/ActionValidators/ActionValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/FieldValidators/FieldValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/JourneyValidators/JourneyValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/ModeValidators/ModeValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/ProjectValidators/ProjectValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/RequirementDefinitionValidators/RequirementDefinitionValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/ResponsibleValidators/ResponsibleValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/StepValidators/StepValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/JourneyRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/PersonRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/ProjectRepository.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/RepositoryBase.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/RequirementTypeRepository.cs, src/Equinor.Procosys.Preservation.Query/GetTagActionDetails/GetActionDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagActions/GetTagActionsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagDetails/GetTagDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagRequirements/GetTagRequirementsQueryHandler.cs, src/Equinor.Procosys.Preservation.WebApi/ProjectAccess/ProjectHelper.cs
Replaced most FirstOrDefaultAsync with SingleOrDefaultAsync.
In the cases where I wasn't sure I put a //TODO, although they are all open for discussion.
=> 72309 replace first or default async

src/Equinor.Procosys.Preservation.Query/GetTagActionDetails/ActionDetailsDto.cs, src/Equinor.Procosys.Preservation.Query/GetTagActionDetails/GetActionDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagActions/ActionDto.cs, src/Equinor.Procosys.Preservation.Query/GetTagActions/GetTagActionsQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/EntityBaseTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActionDetails/GetActionDetailsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagActions/GetTagActionsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/Equinor.Procosys.Preservation.Test.Common.csproj, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/TestEntityBaseExtensions.cs
rowversion changes for endpoints:
GET /Tags/{id}/Actions
GET /Tags/{id}/Actions/{actionId}
Would be great if someone could look over these and leave a comment so I know I'm on the right track for the rest.
=> first two endpoints for review

pipelines/api-build.yml, src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj, src/Equinor.Procosys.Preservation.WebApi/Misc/KeyVaultSettings.cs, src/Equinor.Procosys.Preservation.WebApi/Program.cs, src/Equinor.Procosys.Preservation.WebApi/appsettings.json
Added deploy to k8s in pipeline. Added possibility to read key vault configuration on startup.
=> K8s deployment

src/Equinor.Procosys.Preservation.Query/GetTags/ActionStatus.cs, src/Equinor.Procosys.Preservation.Query/GetTags/GetTagsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTags/TagDto.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/GetTagsQueryHandlerTests.cs
In new TagDto this will be represented by ActionStatus=null which can be used when representing Action icon for a tag (ActionStatus=null => no icon)
=> Removed ActionStatus None

pipelines/api-build.yml, src/Equinor.Procosys.Preservation.WebApi/Dockerfile
Running the app as a specified user in container. Exposing port 5000.
=> Dockerfile

src/Equinor.Procosys.Preservation.Query/GetTags/GetTagsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTags/TagDto.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/TagDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/TagsResultTests.cs
Added readyToBeCompleted in TagDto
=> Added readyToBeCompleted in TagDto

src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200504132707_ChangedSomeDeleteBehaviorCascadeToNoAction.cs
Minor fix on automatic generated DropForeignKey which tried to drop a non-existing foreign key
=> Bugfix in Migration

src/Equinor.Procosys.Preservation.MainApi/Tag/MainApiTagService.cs, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Tag/MainApiTagServiceTests.cs
also fixed tests: they where incorrect setup regarding MaxAvailable returned from Main webapi
=> 73583 - Bufix to prevent extra roundtrip to Main WebApi when seaching tags.

src/Equinor.Procosys.Preservation.Command/ModeCommands/DeleteMode/DeleteModeCommand.cs, src/Equinor.Procosys.Preservation.Command/ModeCommands/DeleteMode/DeleteModeCommandHandler.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Modes/DeleteModeDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Modes/ModesController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/DeleteMode/DeleteModeCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/DeleteMode/DeleteModeCommandTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/ModeCommands/DeleteMode/DeleteModeCommandValidatorTests.cs
Add optimistic concurrency functionality to delete mode endpoint
=> OC for Delete mode

src/Equinor.Procosys.Preservation.Query/GetActionAttachment/GetActionAttachmentQuery.cs, src/Equinor.Procosys.Preservation.Query/GetActionAttachment/GetActionAttachmentQueryHandler.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActionAttachment/GetActionAttachmentQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActionAttachment/GetActionAttachmentQueryTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/AccessValidatorTests.cs
Endpoint for download attachment from an action
Tests
=> 73444 download attachment from action

src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Journey.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Step.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementType.cs, src/Equinor.Procosys.Preservation.Query/JourneyAggregate/GetAllJourneysQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs
@demissie Please review this. Here is stuff you should use in your current work regarding swapping and checking for adjacent steps
=> 73961 refactor step sort key

src/Equinor.Procosys.Preservation.Query/GetActions/GetActionsQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetActions/GetActionsQueryHandlerTests.cs
sort action list as such:
1. Open actions with due time, sorted by due time (oldest dates first)
2. Open actions _without_ due time, sorted by modified date and then created date (oldest dates first)
3. Closed actions, sorted the same way as open actions.  
test
=> 73743 sort action list

src/Equinor.Procosys.Preservation.WebApi/Controllers/Journeys/JourneysController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Journeys/PairedStepIdWithRowVersiondto.cs
Minor rename .... look better for clients
=> Rename propertiers in Dto for SwapSteps endpoint

src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/UnvoidTagFunction/UnvoidTagFunctionCommand.cs, src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/UnvoidTagFunction/UnvoidTagFunctionCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/UnvoidTagFunction/UnvoidTagFunctionCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/VoidTagFunction/VoidTagFunctionCommand.cs, src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/VoidTagFunction/VoidTagFunctionCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagFunctionCommands/VoidTagFunction/VoidTagFunctionCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagFunctionValidators/ITagFunctionValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagFunctionValidators/TagFunctionValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/TagFunctions/TagFunctionsController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/TagFunctions/UnvoidTagFunctionDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/TagFunctions/VoidTagFunctionDto.cs, src/Equinor.Procosys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagFunctionCommands/UnvoidTagFunction/UnvoidTagFunctionCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagFunctionCommands/UnvoidTagFunction/UnvoidTagFunctionCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagFunctionCommands/VoidTagFunction/VoidTagFunctionCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagFunctionCommands/VoidTagFunction/VoidTagFunctionCommandValidatorTests.cs
endpoints:
/TagFunctions/{code}/Void
/TagFunctions/{code}/Unvoid
=> 74245 void unvoid tag function

src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementDefinition.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementUsage.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/RequirementDefinitionConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200604084929_RequirementUsage.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200604084929_RequirementUsage.cs
Commented code in ReqDef constructor will be taken in in next PR.
This PR is DB changes only
=> 74312 db requirement usage in requirement def

src/Equinor.Procosys.Preservation.Command/Validators/StepValidators/StepValidator.cs
See commit message
(Difficult to create unit-test on this one)
=> 74731-Bugfix in validator to honor SortKey when getting first step

src/Equinor.Procosys.Preservation.Query/GetTagRequirements/GetTagRequirementsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagRequirements/RequirementDto.cs
IsVoided on Requirement is needed when editing tag.
=> 73944 IsVoided added in TagRequirementsDto

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommand.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommandHandler.cs, src/Equinor.Procosys.Preservation.MainApi/Client/BearerTokenApiClient.cs, src/Equinor.Procosys.Preservation.MainApi/Client/IBearerTokenApiClient.cs, src/Equinor.Procosys.Preservation.MainApi/Tag/ITagApiService.cs, src/Equinor.Procosys.Preservation.MainApi/Tag/MainApiTagService.cs, src/Equinor.Procosys.Preservation.MainApi/Tag/ProcosysTagDetails.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Client/BearerTokenApiClientTests.cs
No tests written since since this is temporary code.
Also minor rewrite in QueryAndDeserialize: When not receiving OK status from Main Api, log error and throw exception instead of logging Debug and do nothing. Must fail if no contact with Main anyhow since we don't get Plants or Permissions for user
=> 74297 74298 migrate and mark tags as migrated

src/Equinor.Procosys.Preservation.BlobStorage/Equinor.Procosys.Preservation.BlobStorage.csproj, src/Equinor.Procosys.Preservation.Command/Equinor.Procosys.Preservation.Command.csproj, src/Equinor.Procosys.Preservation.Infrastructure/Equinor.Procosys.Preservation.Infrastructure.csproj, src/Equinor.Procosys.Preservation.MainApi/Equinor.Procosys.Preservation.MainApi.csproj, src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj, src/tests/Equinor.Procosys.Preservation.Command.Tests/Equinor.Procosys.Preservation.Command.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Equinor.Procosys.Preservation.Infrastructure.Tests.csproj, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Equinor.Procosys.Preservation.MainApi.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Query.Tests/Equinor.Procosys.Preservation.Query.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Test.Common/Equinor.Procosys.Preservation.Test.Common.csproj, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Equinor.Procosys.Preservation.WebApi.Tests.csproj
=> Updated NuGet packages.

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommandHandler.cs, src/Equinor.Procosys.Preservation.MainApi/Area/MainApiAreaService.cs, src/Equinor.Procosys.Preservation.MainApi/Discipline/MainApiDisciplineService.cs, src/Equinor.Procosys.Preservation.MainApi/Project/MainApiProjectService.cs, src/Equinor.Procosys.Preservation.MainApi/Responsible/MainApiResposibleService.cs, src/Equinor.Procosys.Preservation.MainApi/Tag/MainApiTagService.cs, src/Equinor.Procosys.Preservation.MainApi/TagFunction/MainApiTagFunctionService.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandHandlerTests.cs
UrlEncode queyparams wich can contain illegal chars
=> Bugfix UrlEncoding

src/Equinor.Procosys.Preservation.Command/SyncCommands/SyncProjects/SyncProjectsCommand.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/FilterValues/FilterValuesController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Misc/CacheController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/RequirementTypesController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Responsibles/ResponsiblesController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagSearchController.cs
(cherry picked from commit edc70512d59798f5585c36147f94b3024511993a)
=> Remove unused usings

src/Equinor.Procosys.Preservation.Command/MiscCommands/Clone/CloneCommandHandler.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ResponsibleAggregate/Responsible.cs, src/Equinor.Procosys.Preservation.Infrastructure/Entityconfigurations/ResponsibleConfiguration.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200619103206_RenameResposibleTitleToDescription.Designer.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200619103206_RenameResposibleTitleToDescription.cs, src/Equinor.Procosys.Preservation.Query/GetUniqueTagResponsibles/GetUniqueTagResponsiblesQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/JourneyAggregate/GetAllJourneysQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/JourneyAggregate/GetJourneyByIdQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/ResponsibleAggregate/GetAllResponsiblesQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/ResponsibleAggregate/ResponsibleDto.cs, src/Equinor.Procosys.Preservation.WebApi/Seeding/Seeders.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/UpdateStep/UpdateStepCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/MiscCommands/Clone/CloneCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementCommands/Preserve/PreserveCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/AutoScopeTags/AutoScopeTagsCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/BulkPreserve/BulkPreserveCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Preserve/PreserveCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/StepTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ResponsibleAggregate/ResponsibleTests.cs, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Repositories/ResponsibleRepositoryTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/JourneyAggregate/JourneyDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/JourneyAggregate/StepDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ResponsibleAggregate/GetAllResponsiblesQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/ResponsibleAggregate/ResponsibleDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Test.Common/ReadOnlyTestsBase.cs
Rename Responsible Title to Description. This to match OnPrem ProCoSys DB
=> 74436 rename responsible property

src/Equinor.Procosys.Preservation.Command/JourneyCommands/CreateStep/CreateStepCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/JourneyValidators/IJourneyValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/JourneyValidators/JourneyValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/ModeValidators/IModeValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/ModeValidators/ModeValidator.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/CreateStep/CreateStepCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/JourneyValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/ModeValidatorTests.cs
Refactor to avoid possible null pointer exception i JourneyValidator to avoid use of ModeAggregate in JourneyValidator
=> 74863-Minor refactor to avoid nullpointer exception

src/Docker-compose.development.yml, src/Docker-compose.yml
Fixed port mapping and mounting of local settings file.
=> Updated docker files.

src/Equinor.Procosys.Preservation.Command/JourneyCommands/UnvoidStep/UnvoidStepCommand.cs, src/Equinor.Procosys.Preservation.Command/JourneyCommands/UnvoidStep/UnvoidStepCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/JourneyCommands/UnvoidStep/UnvoidStepCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/JourneyCommands/VoidStep/VoidStepCommand.cs, src/Equinor.Procosys.Preservation.Command/JourneyCommands/VoidStep/VoidStepCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/JourneyCommands/VoidStep/VoidStepCommandValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/JourneyAggregate/Journey.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Journeys/JourneysController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Journeys/UnvoidStepDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Journeys/VoidStepDto.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/UnvoidStep/UnvoidStepCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/UnvoidStep/UnvoidStepCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/VoidStep/VoidStepCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/JourneyCommands/VoidStep/VoidStepCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs
endpoints:
/Journeys/{id}/Steps/{stepId}/Void
/Journeys/{id}/Steps/{stepId}/Unvoid
=> 84878 void unvoid step

src/Equinor.Procosys.Preservation.Command/SyncCommands/SyncProjects/SyncProjectsCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/AutoScopeTags/AutoScopeTagsCommand.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/CreateTags/CreateTagsCommand.cs, src/Equinor.Procosys.Preservation.MainApi/Tag/ITagApiService.cs, src/Equinor.Procosys.Preservation.MainApi/Tag/MainApiTagService.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/SyncCommands/SyncProjects/SyncProjectsCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Tag/MainApiTagServiceTests.cs
See commit message on https://github.com/equinor/procosys-preservation-api/commit/8eadc519fa9e348eef242577263c0bade695aa19
=> 74886 BUGFIX when scoping many tags

src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommand.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Authorizations/AccessValidatorTests.cs
=> 74969 bugfix tag has no due after adding new requirement

src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementType/DeleteRequirementTypeCommand.cs, src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementType/DeleteRequirementTypeCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/RequirementTypeCommands/DeleteRequirementType/DeleteRequirementTypeCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/RequirementTypeValidators/IRequirementTypeValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/RequirementTypeValidators/RequirementTypeValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/DeleteRequirementTypeDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/RequirementTypesController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/DeleteRequirementType/DeleteRequirementTypeCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/RequirementTypeCommands/DeleteRequirementType/DeleteRequirementTypeCommandValidatorTests.cs
Delete requirement type endpoint and tests.
=> Feature/75275   delete requirement type

src/Equinor.Procosys.Preservation.Query/GetTags/GetTagsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTags/TagDto.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/TagDtoTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTags/TagsResultTests.cs
Added ResponsibleDescription field to TagDto and GET tags endpoint.
=> 75413 - Add responsible description to GET tags endpoint

src/Equinor.Procosys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.Procosys.Preservation.WebApi/Startup.cs, src/Equinor.Procosys.Preservation.WebApi/Synchronization/SynchronizationService.cs, src/Equinor.Procosys.Preservation.WebApi/Telemetry/ApplicationInsightsTelemetryClient.cs, src/Equinor.Procosys.Preservation.WebApi/Telemetry/ConsoleTelemetryClient.cs, src/Equinor.Procosys.Preservation.WebApi/Telemetry/ITelemetryClient.cs
Added reporting of custom telemetry (events and metrics) to monitor synchronization service. Added console logger client for offline debug.
=> Added reporting of custom telemetry

src/Equinor.Procosys.Preservation.Query/GetHistoricalFieldValueAttachment/GetHistoricalFieldValueAttachmentQuery.cs, src/Equinor.Procosys.Preservation.Query/GetHistoricalFieldValueAttachment/GetHistoricalFieldValueAttachmentQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetPreservationRecord/GetPreservationRecordQuery.cs, src/Equinor.Procosys.Preservation.Query/GetPreservationRecord/GetPreservationRecordQueryHandler.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetHistoricalFieldValueAttachment/GetHistoricalFieldValueAttachmentQueryHandlerTests.cs
Endpoint to get attachment download link for historical attachments.
Tests.
=> Feature/75592   endpoint for historical attachmentlink

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
Added RequirementPreservedEvent on bulk preservation
=> 75608 - API - Bulk preservation does not record history events

src/Equinor.Procosys.Preservation.Query/GetTagDetails/GetTagDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagDetails/TagDetailsDto.cs
Add IsVoided on tagDetailsDto to be used on tag flyout
=> 75708: IsVoided on tagDetailsDto

src/Equinor.Procosys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.Procosys.Preservation.WebApi/Permissions.cs, src/Equinor.Procosys.Preservation.WebApi/Startup.cs, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Client/BearerTokenApiClientTests.cs, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Permission/MainApiPermissionServiceTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Caches/PlantCacheTests.cs
while coding in Library repo on PBI 73503
=> Minors fixes

src/Equinor.Procosys.Preservation.Command/PersonCommands/CreateSavedFilter/CreateSavedFilterCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/PersonCommands/DeleteSavedFilter/DeleteSavedFilterCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/PersonCommands/UpdateSavedFilter/UpdateSavedFilterCommand.cs, src/Equinor.Procosys.Preservation.Command/PersonCommands/UpdateSavedFilter/UpdateSavedFilterCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/PersonCommands/UpdateSavedFilter/UpdateSavedFilterCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/SavedFilterValidators/ISavedFilterValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/SavedFilterValidators/SavedFilterValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/PersonAggregate/IPersonRepository.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/PersonAggregate/SavedFilter.cs, src/Equinor.Procosys.Preservation.Infrastructure/Repositories/PersonRepository.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/PersonsController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/UpdateSavedFilterDto.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/PersonCommands/CreateSavedFilter/CreateSavedFilterCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/PersonCommands/DeleteSavedFilter/DeleteSavedFilterCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/PersonCommands/UpdateSavedFilter/UpdateSavedFilterCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/PersonCommands/UpdateSavedFilter/UpdateSavedFilterCommandValidatorTests.cs
be able to update title, criteria or defaultfilter true/false. 
if there is an existing defaultfilter for person in current project, clear.
=> 75290 update saved filter endpoint

src/Equinor.Procosys.Preservation.Query/GetSavedFiltersInProject/GetSavedFiltersInProjectQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetSavedFiltersInProject/SavedFilterDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/PersonsController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/UpdateSavedFilterDto.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/PersonCommands/CreateSavedFilter/CreateSavedFilterCommandHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetSavedFiltersInProject/GetSavedFiltersInProjectQueryHandlerTests.cs
return id on GET endpoint in order to use it in PUT endpoint.
rename typo, defaultvalue --> defaultfilter to match all other endpoints
=> Bugfix 75288 get saved filters return id

src/Equinor.Procosys.Preservation.Infrastructure/Caching/CacheManager.cs, src/Equinor.Procosys.Preservation.Infrastructure/Migrations/20200811072634_RemoveRequirementTypeIconMeasure.cs, src/Equinor.Procosys.Preservation.MainApi/Client/BearerTokenApiClient.cs, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Caching/CacheManagerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Caches/PermissionCacheTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Caches/PlantCacheTests.cs
=> Minor fixes

src/Equinor.Procosys.Preservation.WebApi/Controllers/RequirementTypes/RequirementTypesController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/TagFunctions/TagFunctionsController.cs
@arildbjerkenes  Check if this is a breaking change for UI
=> Bug endpoints returning wrong structure

src/Equinor.Procosys.Preservation.Query/GetRequirementTypeById/FieldDetailsDto.cs, src/Equinor.Procosys.Preservation.Query/GetRequirementTypeById/GetRequirementTypeByIdQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagRequirementTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetRequirementTypeById/GetRequirementTypeByIdQueryHandlerTests.cs
First part of creating logic for Delete of fields
=> 76377 Extend FieldDto with IsInUse property

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementType.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/ProjectTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/RequirementTypeAggregate/RequirementTypeTests.cs
Code has some ToDo's regarding write more tests.
This PR is some of them
=> 77641 missing unit tests

src/Equinor.Procosys.Preservation.WebApi/Excel/ExcelConverter.cs
Fix last minute hack from last sprint. Solution explained at github
https://github.com/ClosedXML/ClosedXML/issues/1509
Ref BUG 78036
=> 78036 - Excel cell formating

src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs, src/Equinor.Procosys.Preservation.WebApi/appsettings.json
This to also use same value in sandbox
=> 78018 - Increase SearchTagsByTagNo

src/Equinor.Procosys.Preservation.WebApi/Startup.cs
@paal123 @kfaln @llykkelarsen  Nice to know. Guess we will meet same problem in all modules
=> 78420 - Fix exception "Multipart body length limit xxx exceeded"

src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
Removed too strict business validator when updating Requirements on a Tag
=> 78445 bug edit tag supplier req

src/Equinor.Procosys.Preservation.Query/GetAllJourneys/GetAllJourneysQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetAllJourneys/GetAllJourneysQueryHandlerTests.cs
isVoided and forSupplier was swapped
=> 78739 bugfix GET journeys endpoint give wrong forSupplier

src/Equinor.Procosys.Preservation.Query/GetTagFunctionDetails/GetTagFunctionDetailsQueryHandler.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagFunctionDetails/GetTagFunctionDetailsQueryHandlerTests.cs
Important to test manually in UI to detect if this is a breaking change or not
=> 78681 get tag function returning null and success when entity not found

src/Equinor.Procosys.Preservation.Command/EventHandlers/HistoryEvents/IntervalChangedEventHandler.cs, src/Equinor.Procosys.Preservation.Command/EventHandlers/HistoryEvents/RequirementPreservedEventHandler.cs, src/Equinor.Procosys.Preservation.Command/EventHandlers/HistoryEvents/StepChangedEventHandler.cs, src/Equinor.Procosys.Preservation.Command/EventHandlers/HistoryEvents/TransferredAutomaticallyEventHandler.cs, src/Equinor.Procosys.Preservation.Command/EventHandlers/HistoryEvents/TransferredManuallyEventHandler.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandHandler.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/HistoryAggregate/EventType.cs, src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.Procosys.Preservation.Domain/Events/StepChangedEvent.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/ActionAddedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/IntervalChangedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/RequirementAddedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/RequirementPreservedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/RequirementUnvoidedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/RequirementVoidedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/StepChangedEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/TransferredAutomaticallyEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/EventHandlers/HistoryEvents/TransferredManuallyEventHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs
=> 78422 Add change of journey in history

src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs, src/Equinor.Procosys.Preservation.MainApi/Client/BearerTokenApiClient.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs
Includes a minor change of a validation message introduced in #437
=> 78854 - Log Info in BearerTokenApiClient

src/Equinor.Procosys.Preservation.Command/TagCommands/CompletePreservation/CompletePreservationCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/Reschedule/RescheduleCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/RescheduleTagsDto.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/RescheduleTagsDtoValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/Reschedule/RescheduleCommandValidatorTests.cs
=> 79174 reschedule endpoint

pipelines/api-build.yml, src/Equinor.Procosys.Preservation.Query/GetTagDetails/GetTagDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagDetails/TagDetailsDto.cs, src/Equinor.Procosys.Preservation.sln, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagDetails/GetTagDetailsQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/IntegrationTestAuthHandler.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/KnownTestData.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/SeedingData.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestFactory.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestProfile.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestsHelper.cs
Did some improvements in integrationtest project while working with IPO in parallell
=> 79486 Extend tag details endpoint with discipline code

src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/Equinor.Procosys.Preservation.WebApi/Controllers/Tags/UpdateTagStepAndRequirementsDto.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/KnownTestData.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/JourneyDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/ModeDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/ResponsibleDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/StepDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestFactory.cs
See commit msgs, specially on https://github.com/equinor/procosys-preservation-api/commit/c930321bcec28f91a72eb9ecefca41517ff4eebe
TestBase.AssertRowVersionChange and usage of it when testing PUT endpoints should be taken into IPO
=> 79547 - BUGFIX - Not able to void tag requirement

src/Equinor.Procosys.Preservation.BlobStorage/Equinor.Procosys.Preservation.BlobStorage.csproj, src/Equinor.Procosys.Preservation.Command/Equinor.Procosys.Preservation.Command.csproj, src/Equinor.Procosys.Preservation.Domain/Equinor.Procosys.Preservation.Domain.csproj, src/Equinor.Procosys.Preservation.Infrastructure/Equinor.Procosys.Preservation.Infrastructure.csproj, src/Equinor.Procosys.Preservation.MainApi/Equinor.Procosys.Preservation.MainApi.csproj, src/Equinor.Procosys.Preservation.Query/Equinor.Procosys.Preservation.Query.csproj, src/Equinor.Procosys.Preservation.Query/GetActionDetails/GetActionDetailsQueryHandler.cs, src/Equinor.Procosys.Preservation.WebApi/Dockerfile, src/Equinor.Procosys.Preservation.WebApi/Equinor.Procosys.Preservation.WebApi.csproj, src/tests/Equinor.Procosys.Preservation.Command.Tests/Equinor.Procosys.Preservation.Command.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Domain.Tests/Equinor.Procosys.Preservation.Domain.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Infrastructure.Tests/Equinor.Procosys.Preservation.Infrastructure.Tests.csproj, src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Equinor.Procosys.Preservation.MainApi.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Query.Tests/Equinor.Procosys.Preservation.Query.Tests.csproj, src/tests/Equinor.Procosys.Preservation.Test.Common/Equinor.Procosys.Preservation.Test.Common.csproj, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Equinor.Procosys.Preservation.WebApi.IntegrationTests.csproj, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Equinor.Procosys.Preservation.WebApi.Tests.csproj
=> 79652 update NuGet pkgs and use .NET5.0

src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTestsBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Misc/HeartbeatControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerTestsBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/TestFactory.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/UserType.cs
=> 79984 improved HttpClient setup for integration tests

src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/PurchaseOrderHelper.cs, src/Equinor.Procosys.Preservation.WebApi/Excel/ExcelConverter.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/KnownTestData.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagDetailsDto.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsBase.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.Procosys.Preservation.WebApi.IntegrationTests/Tags/XLFile.cs
Made integration tests before changing logic. Next thing to do is to expand Tag tab in excelconverter with more columns
=> 80304 Integration tests for ExportTagsToExcel

src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportHistoryDto.cs, src/Equinor.Procosys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.Procosys.Preservation.WebApi/Excel/ExcelConverter.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs, src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Excel/ExcelConverterTests.cs
Yet a fix: Missed User column in Excel sheet with History
=> 80421 details in history in excel bugfix2

src/Equinor.Procosys.Preservation.WebApi/Controllers/Persons/PersonsController.cs
PRESERVATION_READ is enough to create, update and delete filters owned by self
=> 80990 Less permissions to update filters

src/Equinor.Procosys.Preservation.Domain/AggregateModels/ProjectAggregate/TagRequirement.cs, src/Equinor.Procosys.Preservation.Query/GetTagRequirements/GetTagRequirementsQueryHandler.cs, src/Equinor.Procosys.Preservation.Query/GetTagRequirements/RequirementDetailsDto.cs, src/Equinor.Procosys.Preservation.Query/ModeAggregate/ModeDto.cs, src/tests/Equinor.Procosys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagRequirementTests.cs, src/tests/Equinor.Procosys.Preservation.Query.Tests/GetTagRequirements/GetTagRequirementsQueryHandlerTests.cs
Part 1 of 2 for implementing delete tag requirement.
This part extend dto with IsUnUse-flag, to be used in frontend to show/hide delete button
=> 79034 delete tagrequirement vol1

src/Equinor.Procosys.Preservation.Command/TagCommands/CreateAreaTag/CreateAreaTagCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/ITagValidator.cs, src/Equinor.Procosys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/CreateAreaTag/CreateAreaTagCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/TagCommands/UpdateTagStepAndRequirements/UpdateTagStepAndRequirementsCommandValidatorTests.cs, src/tests/Equinor.Procosys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
Forgotten commit from last PR .... codereview touchups
[AB#82120](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82120)
=> 82120 allow supplier requirement only for PO

src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs
[AB#82167](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82167)
=> 82167 - Tech - stabilize integration tests

src/Equinor.ProCoSys.Preservation.BlobStorage/Equinor.ProCoSys.Preservation.BlobStorage.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
Monthly nuget updates for April
=> Preservation API - Update NuGet packages [April]

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/SettingAggregate/Setting.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/SynchronizationService.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/TagValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTags/GetTagsQueryHandlerTests.cs
See commit msgs
[AB#82548](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82548)
=> 82548 - Bug - Mode do not change on rfcc accept

pipelines/api-build.yml
Completes [AB#82751](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82751)
=> Add replicas parameter

src/Equinor.ProCoSys.Preservation.Command/JourneyCommands/CreateStep/CreateStepCommandValidator.cs, src/Equinor.ProCoSys.Preservation.Command/JourneyCommands/SwapSteps/SwapStepsCommandHandler.cs, src/Equinor.ProCoSys.Preservation.Command/JourneyCommands/SwapSteps/SwapStepsCommandValidator.cs, src/Equinor.ProCoSys.Preservation.Command/JourneyCommands/UpdateStep/UpdateStepCommandValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/ModeValidators/IModeValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/StepValidators/IStepValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/StepValidators/StepValidator.cs, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Journeys/JourneysController.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/JourneyCommands/CreateStep/CreateStepCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/JourneyCommands/SwapSteps/SwapStepsCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/JourneyCommands/UpdateStep/UpdateStepCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/ModeValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/StepValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTestsBase.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/ResponsibleDto.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/StepDetailsDto.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/StepIdAndRowVersion.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/StepIdWithRowVersiondto.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/KnownTestData.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/PreservationContextExtension.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsBase.cs
See commit msgs
[AB#82464](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82464)
=> 82464  - Remove preservation journey supplier business rules

src/Equinor.ProCoSys.Preservation.WebApi/Authorizations/AuthorizationOptions.cs, src/Equinor.ProCoSys.Preservation.WebApi/Authorizations/CrossPlantAccessChecker.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Authorizations/AuthorizationOptionsTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Authorizations/CrossPlantAccessCheckerTests.cs
[AB#82463](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82463)
=> 82463 trace more info regarding cross plant access check

src/Equinor.ProCoSys.Preservation.Command/TagCommands/Transfer/TransferCommandValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/TagValidators/ITagValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/TagValidators/TagValidator.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagCommands/Transfer/TransferCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
bugfix after opening for supplier step at any place in journey: When transfer, need to check if Tag as requirement usage in next step according to if step is for supplier or not
[AB#82464](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82464)
=> 82464 - remove preservation journey supplier business rules bugfix

src/Equinor.ProCoSys.Preservation.Command/PersonCommands/CreatePerson/CreatePersonCommand.cs, src/Equinor.ProCoSys.Preservation.Command/PersonCommands/CreatePerson/CreatePersonCommandHandler.cs, src/Equinor.ProCoSys.Preservation.MainApi/Person/IPersonApiService.cs, src/Equinor.ProCoSys.Preservation.MainApi/Person/MainApiPersonService.cs, src/Equinor.ProCoSys.Preservation.MainApi/Person/PCSPerson.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/Middleware/VerifyOidInDbMiddleware.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/ActionAttachmentCommands/Upload/UploadActionAttachmentCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/PersonCommands/CreatePerson/CreatePersonCommandHandlerTest.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs
[AB#83375](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/83375)
=> 83375 make machine to machine authentication possible

pipelines/api-build.yml
[AB#82068](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82068)
=> 82068 - Add new parameteres to pipeline yml

pipelines/api-build.yml
[AB#82068](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82068)
=> 82068 - Set correct aspNetCoreEnvironment in Test and Production

src/Equinor.ProCoSys.Preservation.WebApi/Authentication/Authenticator.cs, src/Equinor.ProCoSys.Preservation.WebApi/Authentication/AuthenticatorOptions.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/SynchronizationService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TimedSynchronizationOptions.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/appsettings.json, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
See commit msgs
[AB#85886](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/85886)
=> 85886 - service principle auth phase1

src/Equinor.ProCoSys.Preservation.Command/PersonCommands/CreatePerson/CreatePersonCommandHandler.cs, src/Equinor.ProCoSys.Preservation.Domain/ICurrentUserProvider.cs, src/Equinor.ProCoSys.Preservation.MainApi/Person/IPersonCache.cs, src/Equinor.ProCoSys.Preservation.WebApi/Authorizations/ClaimsTransformation.cs, src/Equinor.ProCoSys.Preservation.WebApi/Caches/CacheOptions.cs, src/Equinor.ProCoSys.Preservation.WebApi/Caches/PersonCache.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/Middleware/GlobalExceptionHandler.cs, src/Equinor.ProCoSys.Preservation.WebApi/Middleware/MiddlewareExtensions.cs, src/Equinor.ProCoSys.Preservation.WebApi/Middleware/PersonValidatorMiddleware.cs, src/Equinor.ProCoSys.Preservation.WebApi/Misc/CurrentUserProvider.cs, src/Equinor.ProCoSys.Preservation.WebApi/Misc/HttpContextExtension.cs, src/Equinor.ProCoSys.Preservation.WebApi/Seeding/Seeder.cs, src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/PersonCommands/CreatePerson/CreatePersonCommandHandlerTest.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/ITestUser.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/IntegrationTestAuthHandler.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Misc/HeartbeatControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/RequirementTypes/RequirementTypesControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestUser.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TokenProfile.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Authorizations/ClaimsTransformationTests.cs
[AB#85886](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/85886)
=> 85886 better handling when no pcs user

src/Equinor.ProCoSys.Preservation.Query/ModeAggregate/ModeDto.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/ModeAggregate/ModeDtoTests.cs
Removing all compiler warnings
=> Removing all compiler warnings

src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs
[AB#87139](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/87139)
=> 87139 - Refactor use of obsolete code

src/Equinor.ProCoSys.Preservation.Command/TagCommands/UndoStartPreservation/UndoStartPreservationCommand.cs, src/Equinor.ProCoSys.Preservation.Command/TagCommands/UndoStartPreservation/UndoStartPreservationCommandHandler.cs, src/Equinor.ProCoSys.Preservation.Command/TagCommands/UndoStartPreservation/UndoStartPreservationCommandValidator.cs, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagCommands/UndoStartPreservation/UndoStartPreservationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagCommands/UndoStartPreservation/UndoStartPreservationCommandTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagCommands/UndoStartPreservation/UndoStartPreservationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagDto.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs
[AB#87771](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/87771)
=> 87771 undo start integration tests

src/Equinor.ProCoSys.Preservation.Infrastructure/PreservationContext.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Modes/ModesControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs
[AB#88576](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88576)
More tests for other entities will come
=> 88576 bugfix handling optimistic concurrency

src/Equinor.ProCoSys.Preservation.BlobStorage/Equinor.ProCoSys.Preservation.BlobStorage.csproj, src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj, src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj, src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj
Updatete to latest .Net 5 release (5.0.13)
=> package update

pipelines/api-build.yml, src/Equinor.ProCoSys.Preservation.BlobStorage/Equinor.ProCoSys.Preservation.BlobStorage.csproj, src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj, src/Equinor.ProCoSys.Preservation.Domain/Equinor.ProCoSys.Preservation.Domain.csproj, src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj, src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj, src/Equinor.ProCoSys.Preservation.Query/Equinor.ProCoSys.Preservation.Query.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Dockerfile, src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj
Purpose: Upgrade project for .net core 6.X. 
The PR MUST happen later than _Dotnet62ndtry #79_ (due to refs. to infra templates)
=> Dotnet2ndtry

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/HistoryAggregate/EventType.cs
[AB#87770](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/87770)
=> 87770 - Minor description change, used in History for the UndoPreservationStarted event

src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj, src/Equinor.ProCoSys.Preservation.Domain/Equinor.ProCoSys.Preservation.Domain.csproj, src/Equinor.ProCoSys.Preservation.Query/Equinor.ProCoSys.Preservation.Query.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Behaviors/CheckAccessBehavior.cs, src/Equinor.ProCoSys.Preservation.WebApi/Behaviors/CheckValidProjectBehavior.cs, src/Equinor.ProCoSys.Preservation.WebApi/Behaviors/LoggingBehavior.cs, src/Equinor.ProCoSys.Preservation.WebApi/Dockerfile, src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
[AB#89065](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/89065)
=> 89065 upgrade NuGets

src/Equinor.ProCoSys.Preservation.MainApi/Client/BearerTokenApiClient.cs
[AB#89555](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/89555)
=> fix: 89555 increase httpclient request timeout to 200 seconds

src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
[AB#90401](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/90401)
=> 90401 enable fetch from deadletterqueue

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/CertificateEventProcessorService.cs
[AB#91042](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/91042)
=> 91042 ProjectName not required in certificate event

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/TagValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTags/GetTagsQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs
[AB#95176](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95176)
Changed rule for when to allow start preservation: Now allow to start after complete
=> 95176 able to start after complete

src/Equinor.ProCoSys.Preservation.Infrastructure/Caching/CacheManager.cs, src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Caching/CacheManagerTests.cs
[AB#95177](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95177)
Improve CacheManager: if cached value is a task, check if that task was Successfully executed before returning cached value. If the cached task failed, don't use the cache but try to execute the task again
NB! This fix must be implemented in IPO too
=> 95177 improve cache

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportRequirementDto.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportTagDto.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.ProCoSys.Preservation.WebApi/Excel/ExcelConverter.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Excel/ExcelConverterTests.cs
[AB#95174](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95174)
=> 95174 Export active preservation comment to excel

src/Equinor.ProCoSys.Preservation.MainApi/Client/BearerTokenApiClient.cs, src/Equinor.ProCoSys.Preservation.MainApi/Tag/MainApiTagService.cs, src/Equinor.ProCoSys.Preservation.Query/TagApiQueries/SearchTags/SearchTagsByTagNoQueryHandler.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/TagApiQueries/SearchTags/SearchTagsByTagNoQueryHandlerTests.cs
[AB#95847](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95847)
=> 95847 calculateMccrResponsibleCodes flag

pipelines/api-build.yml, src/Equinor.ProCoSys.Preservation.Infrastructure/PreservationContext.cs, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Misc/HeartbeatController.cs, src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs, src/Equinor.ProCoSys.Preservation.WebApi/Telemetry/ApplicationInsightsTelemetryClient.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
[AB#96092](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96092)
(most changes in https://github.com/equinor/procosys-preservation-api/pull/804/commits/141f6f5ef38c9b827888526aa21d477fb303ce48 will be reverted before merge ... just for testing deploy to dev from working branch)
=> 96092 use connstring to ai

src/Equinor.ProCoSys.Preservation.BlobStorage/Equinor.ProCoSys.Preservation.BlobStorage.csproj, src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj, src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj, src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/Equinor.ProCoSys.Preservation.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.MainApi.Tests/Equinor.ProCoSys.Preservation.MainApi.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/Equinor.ProCoSys.Preservation.Query.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Test.Common/Equinor.ProCoSys.Preservation.Test.Common.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj
[AB#96689](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96689)
=> 96689 Handle delete behavior bus events (and updage nuget non breaking)

src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
[AB#96798](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96798)
=> 96798 - Downgrade ClosedXMLto version 0.96.

src/Equinor.ProCoSys.Preservation.MainApi/Client/BearerTokenApiClient.cs, src/Equinor.ProCoSys.Preservation.MainApi/Client/IBearerTokenApiClient.cs, src/Equinor.ProCoSys.Preservation.MainApi/Me/IMeApiService.cs, src/Equinor.ProCoSys.Preservation.MainApi/Me/MainApiMeService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Caches/PermissionCache.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Caches/PermissionCacheTests.cs
[AB#96979](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96979)
=> 96979 use traceplant

src/Equinor.ProCoSys.Preservation.Command/TagCommands/FillPCSGuids/FillPCSGuidsCommand.cs, src/Equinor.ProCoSys.Preservation.Command/TagCommands/FillPCSGuids/FillPCSGuidsCommandHandler.cs, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/Equinor.ProCoSys.Preservation.Infrastructure/Repositories/ProjectRepository.cs, src/Equinor.ProCoSys.Preservation.MainApi/Tag/ITagApiService.cs, src/Equinor.ProCoSys.Preservation.MainApi/Tag/MainApiTagService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/ISynchronizationService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/SynchronizationOptions.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/SynchronizationService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TimedSynchronization.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagCommands/AutoScopeTags/AutoScopeTagsCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/TagCommands/CreateTags/CreateTagsCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs
[AB#98405](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98405)
Temporary code to be used once in each environment. To populate ProCoSysGUID into all existing StandardTags in preservation
=> 98405 populate pcs guid

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/SynchronizationOptions.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TimedSynchronization.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
[AB#98405](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98405)
=> 98405 - SynchronizationOptions to decide which machine to do work on

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TimedSynchronization.cs
[AB#98405](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98405)
=> 98405 - Need to start timer in each interval

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs
[AB#96688](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96688)
=> 96688 - Change ordering of History events when IsVoidedInSource and IsDeletedInSource

src/Equinor.ProCoSys.Preservation.Query/GetTagDetails/GetTagDetailsQueryHandler.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagDetails/TagDetailsDto.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagDetails/GetTagDetailsQueryHandlerTests.cs
[AB#96688](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96688)
Expose IsVoidedInSource and IsDeletedInSource: To be used Frontend to show these states in Details frame
=> 96688 - Expose IsVoidedInSource and IsDeletedInSource

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/CommPkgTmpTopic.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/McPkgTmpTopic.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/ProjectTmpTopic.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/ResponsibleTmpTopic.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TagFunctionTmpTopic.cs
[AB#98517](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98517)
=> 98517 - Temporary topics with string as ProCoSysGuids

src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TimedSynchronization.cs
[AB#98551](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98551)
Code kept, since we likely need something similar later
=> 98551 - Comment out code which start timerjob

src/Equinor.ProCoSys.Preservation.Command/JourneyCommands/DeleteJourney/DeleteJourneyCommandValidator.cs, src/Equinor.ProCoSys.Preservation.Command/JourneyCommands/DeleteStep/DeleteStepCommandValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/JourneyValidators/IJourneyValidator.cs, src/Equinor.ProCoSys.Preservation.Command/Validators/JourneyValidators/JourneyValidator.cs, src/Equinor.ProCoSys.Preservation.Infrastructure/Repositories/JourneyRepository.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/JourneyCommands/DeleteJourney/DeleteJourneyCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/JourneyCommands/DeleteStep/DeleteStepCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/JourneyValidatorTests.cs, src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Repositories/JourneyRepositoryTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Journeys/JourneysControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestBase.cs
[AB#98580](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98580)
Now a Journey can be deleted if it has steps, but no step in Journey can't have a tag
=> 98580 - Change rule when a Journey can be deleted

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTags/GetTagsQueryHandler.cs
=> 98703 Add queryable.tagwith to all db queries

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTags/GetTagsQueryHandler.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs
[AB#98716](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98716)
=> 98716 - more logging

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.ProCoSys.Preservation.WebApi/Excel/ExcelConverter.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Excel/ExcelConverterTests.cs
[AB#98716](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98716)
=> 98716 - even more logging

src/Equinor.ProCoSys.Preservation.Domain/Time/Timer.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.ProCoSys.Preservation.WebApi/Excel/ExcelConverter.cs
[AB#98716](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98716)
=> 98716 - Try AsSplitQuery

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs
[AB#98716](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98716)
=> 98716 - Use SplitQuery globally

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagDto.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs
[AB#98931](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98931)
Not ready to undo start in status In ser4vice
=> 98931 - Integration tests for new status In service

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/PreservationPeriod.cs, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/Field.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagRequirementTests.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/RequirementTypeAggregate/FieldTests.cs
[AB#99990](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/99990)
=> 99990 - Field.NeedsUserInput should honor IsVoided

src/Equinor.ProCoSys.Preservation.Command/ProjectCommands/FillPCSGuids/FillPCSGuidsCommandHandler.cs, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs, src/Equinor.ProCoSys.Preservation.Infrastructure/Repositories/ProjectRepository.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/TimedSynchronization.cs
Laget en ny versjon av denne basert på siste master og tok abandon på den forrige PR'en
=> Comment out on-time migration

src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/JourneyAggregate/Journey.cs, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/JourneyAggregate/JourneyTests.cs, src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/TagTests.cs
[AB#102031](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/102031)
=> 102031 - Allow transfer when in service

src/Equinor.ProCoSys.Preservation.Domain/TagOptions.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportHistoryDto.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/ExportTagDto.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExportQuery.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/HistoryExportMode.cs, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/Equinor.ProCoSys.Preservation.WebApi/Excel/ExcelConverter.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Excel/ExcelConverterTests.cs
[AB#102190](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/102190)
=> 102190 history for many tags

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExcelQueryHandler.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/GetTagsForExportQuery.cs, src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsForExport/HistoryExportMode.cs, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Tags/TagsController.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTagsForExport/GetTagsForExportQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Tags/TagsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Controllers/Tags/TagsControllerForGetExcelDocumentTests.cs
[AB#102394](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/102394)
=> 102394 sanitize code history for one tag

src/Equinor.ProCoSys.Preservation.Command/Equinor.ProCoSys.Preservation.Command.csproj, src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/IProjectRepository.cs, src/Equinor.ProCoSys.Preservation.Domain/Equinor.ProCoSys.Preservation.Domain.csproj, src/Equinor.ProCoSys.Preservation.Domain/Events/ActionAddedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/ActionClosedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/IntervalChangedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/PreservationCompletedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/PreservationSetInServiceEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/PreservationStartedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/RescheduledEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/StepChangedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagCreatedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagDeletedInSourceEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementAddedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementDeletedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementPreservedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementUnvoidedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementVoidedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagUnvoidedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagUnvoidedInSourceEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagVoidedEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TagVoidedInSourceEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TransferredAutomaticallyEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/TransferredManuallyEvent.cs, src/Equinor.ProCoSys.Preservation.Domain/Events/UndoPreservationStartedEvent.cs, src/Equinor.ProCoSys.Preservation.Infrastructure/Repositories/ProjectRepository.cs, src/Equinor.ProCoSys.Preservation.MainApi/Equinor.ProCoSys.Preservation.MainApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Controllers/Misc/CacheController.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/EventHandlers/EventDispatcherTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
[AB#104185](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104185)
=> 104185 latest common

src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs, src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/CertificateEventProcessorService.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
[AB#105392](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105392) 
Update pcsBus-nuget package
=> 105392 - Handle only accepted certificates

pipelines/api-build.yml
[AB#105863](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105863)
=> 105863 - Use latest of leader elector

src/Equinor.ProCoSys.Preservation.WebApi/Middleware/CurrentPlantMiddleware.cs
[AB#107214](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107214)
=> 107214 - more logging in CurrentPlantMiddleware

radixconfig.yaml
=> 108176 radix promote fix

radixconfig.yaml
[AB#107301](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107301)
=> 107301 - Modify cpu and memory for prod

src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj
https://github.com/equinor/cc-toolbox/issues/933
=> 933 - Update ClosedXML to fix vulnerability in System.IO.Packaging

radixconfig.yaml
https://github.com/equinor/cc-toolbox/issues/1064
=> 1064 test environment high memory usage

radixconfig.yaml, src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
Configuration cleanup. Migrating non-secret configuration from the app configuration service to appsettings or radix configuration files.
If the configuration is common to all environments, it is added to appsettings. If it is environment specific, it is added to radix.
https://github.com/equinor/cc-toolbox/issues/1064
=> 1064 config refactor

radixconfig.yaml, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/AuthenticationConfig.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/SetupAppConfig.cs, src/Equinor.ProCoSys.Preservation.WebApi/Program.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
Replacing app configuration connection string authentication with credential authentication.
=> 1073 app config authentication refactor

radixconfig.yaml, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ServiceBusConfig.cs, src/Equinor.ProCoSys.Preservation.WebApi/Equinor.ProCoSys.Preservation.WebApi.csproj, src/Equinor.ProCoSys.Preservation.WebApi/Misc/GetConfig.cs, src/Equinor.ProCoSys.Preservation.WebApi/Program.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/appsettings.json, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Misc/GetConfigTests.cs
Using token credential to authenticate service bus connection
Bus sender authentication change: https://github.com/equinor/procosys-bus-sender-worker-service/pull/167
https://github.com/equinor/cc-toolbox/issues/1065
=> 1065 service bus authentication

src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj
=> Downgrade SqlClient to version 5.2.1

pipelines/preservation-pipeline.yml, radixconfig.yaml, src/Equinor.ProCoSys.Preservation.Infrastructure/Equinor.ProCoSys.Preservation.Infrastructure.csproj, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/TestFactory.cs
Version 5.2.0 has allows for workload identity authentication through the connection string. Reverting previous implementation, updating the package version and using a more elegant connection string implementation.
https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#using-workload-identity-authentication
Link to accompanying infra change: https://github.com/equinor/procosys-infra/pull/993
https://github.com/equinor/cc-toolbox/issues/1071
=> 1071 db auth refactor

src/Equinor.ProCoSys.Preservation.Infrastructure/Migrations/20250221084531_SavedFiltersMigrations.Designer.cs, src/Equinor.ProCoSys.Preservation.Infrastructure/Migrations/20250221084531_SavedFiltersMigrations.cs, src/Equinor.ProCoSys.Preservation.WebApi/Program.cs
https://github.com/equinor/cc-toolbox/issues/1020
=> 1020 saved filters do not work

pipelines/preservation-pipeline.yml, radixconfig.yaml, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/TelemetryConfig.cs, src/Equinor.ProCoSys.Preservation.WebApi/Program.cs, src/Equinor.ProCoSys.Preservation.WebApi/appsettings.json
Using identity credentials to authenticate application insights connection
=> 1113 application insights identity auth

src/Equinor.ProCoSys.Preservation.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/MassTransitConfig.cs, src/Equinor.ProCoSys.Preservation.WebApi/DiModules/SetupDatabase.cs, src/Equinor.ProCoSys.Preservation.WebApi/Program.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/SetupDatabaseTests.cs
* Migrating MigrateDatabase, SeedDummyData, and DebugEntityFrameworkInDevelopment configurations into the Application section
* Disabling mass transit service bus configuration when service bus is disabled
https://github.com/equinor/cc-toolbox/issues/1098
=> 1098 config refactor

src/Equinor.ProCoSys.Preservation.Query/GetTagsQueries/GetTagsQueryBase.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetTagsQueries/GetTags/GetTagsQueryHandlerTests.cs
https://github.com/equinor/cc-toolbox/issues/1210
=> 1210 - Get tags should exclude voided requirements when filter on requirements

src/Equinor.ProCoSys.Preservation.Query/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryHandler.cs, src/tests/Equinor.ProCoSys.Preservation.Query.Tests/GetUniqueTagRequirementTypes/GetUniqueTagRequirementTypesQueryHandlerTests.cs
Extra for 1210: Also exclude voided Tag Requirements from available Requirement types used in filter
https://github.com/equinor/cc-toolbox/issues/1210
=> Extra for 1210: Also exclude voided Tag Requirements from filter

src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Equinor.ProCoSys.Preservation.Command.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/EventHandlers/IntegrationEvents/CreateTagRequirementDeleteEventHelperTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/EventHandlers/IntegrationEvents/TagDeletedEventHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.Command.Tests/EventHandlers/IntegrationEvents/TagRequirementDeletedEventHandlerTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Equinor.ProCoSys.Preservation.WebApi.Tests.csproj, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Misc/GetConfigTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Misc/IsServiceBusEnabledTests.cs, src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/SetupDatabaseTests.cs
Replacing fluent assertions with regular assertions. Fluent assertions now require a paid license.
https://github.com/equinor/cc-toolbox/issues/1686
=> 1686 fluent assertions
